class Portuguese:
    conjugaisonV1 = {
        "o":"Présent",
        "as":"Présent",
        "a":"Présent",
        "amos":"Présent",
        "ais":"Présent",
        "am":"Présent",
        "ava":"Imparfait",
        "avas":"Imparfait",
        "ávamos":"Imparfait",
        "áveis":"Imparfait",
        "avam":"Imparfait",
        "ara":"Plus-que-parfait",
        "aras":"Plus-que-parfait",
        "áramos":"Plus-que-parfait",
        "áreis":"Plus-que-parfait",
        "aram":"Plus-que-parfait",
        "ei":"Passé Simple",
        "aste":"Passé Simple",
        "ou":"Passé Simple",
        "ámos":"Passé Simple",
        "astes":"Passé Simple",
        "aram":"Passé Simple",
        "arei":"Futur Simple",
        "arás":"Futur Simple",
        "ará":"Futur Simple",
        "aremos":"Futur Simple",
        "areis":"Futur Simple",
        "arão":"Futur Simple",
        "aria":"Conditionnel Simple",
        "arias":"Conditionnel Simple",
        "aríamos":"Conditionnel Simple",
        "aríeis":"Conditionnel Simple",
        "ariam":"Conditionnel Simple",
        "e":"Subjonctif Présent",
        "es":"Subjonctif Présent",
        "emos":"Subjonctif Présent",
        "eis":"Subjonctif Présent",
        "em":"Subjonctif Présent",
        "asse":"Subjonctif Imparfait",
        "asses":"Subjonctif Imparfait",
        "ássemos":"Subjonctif Imparfait",
        "ásseis":"Subjonctif Imparfait",
        "assem":"Subjonctif Imparfait",
        "ar":"Futur Simple",
        "ares":"Futur Simple",
        "armos":"Futur Simple",
        "ardes":"Futur Simple",
        "arem":"Futur Simple",
        "ado":"Participe",
        "ando":"Gérondif"
    }

    conjugaisonV2 = {
        "o":"Présent Simple",
        "es":"Présent Simple",
        "emos":"Présent Simple",
        "eis":"Présent Simple",
        "em":"Présent Simple",
        "ia":"Imparfait",
        "ias":"Imparfait",
        "íamos":"Imparfait",
        "íeis":"Imparfait",
        "iam":"Imparfait",
        "era":"Plus-que-parfait",
        "eras":"Plus-que-parfait",
        "êramos":"Plus-que-parfait",
        "êreis":"Plus-que-parfait",
        "eram":"Plus-que-parfait",
        "i":"Passé Simple",
        "este":"Passé Simple",
        "eu":"Passé Simple",
        "emos":"Passé Simple",
        "estes":"Passé Simple",
        "eram":"Passé Simple",
        "erei":"Futur Simple",
        "erás":"Futur Simple",
        "erá":"Futur Simple",
        "eremos":"Futur Simple",
        "ereis":"Futur Simple",
        "erão":"Futur Simple",
        "eria":"Conditionnel Présent",
        "erias":"Conditionnel Présent",
        "eríamos":"Conditionnel Présent",
        "eríeis":"Conditionnel Présent",
        "eriam":"Conditionnel Présent",
        "a":"Subjonctif Présent",
        "as":"Subjonctif Présent",
        "amos":"Subjonctif Présent",
        "ais":"Subjonctif Présent",
        "am":"Subjonctif Présent",
        "esse":"Subjonctif Imparfait",
        "esses":"Subjonctif Imparfait",
        "êssemos":"Subjonctif Imparfait",
        "êsseis":"Subjonctif Imparfait",
        "essem":"Subjonctif Imparfait",
        "er":"Futur Simple",
        "eres":"Futur Simple",
        "ermos":"Futur Simple",
        "erdes":"Futur Simple",
        "erem":"Futur Simple",
        "endo":"Gérondif",
        "ido":"Participe"
    }

    conjugaisonV3 = {
        "o":"Présent Simple",
        "es":"Présent Simple",
        "e":"Présent Simple",
        "imos":"Présent Simple",
        "is":"Présent Simple",
        "em":"Présent Simple",
        "ia":"Imparfait",
        "ias":"Imparfait",
        "íamos":"Imparfait",
        "íeis":"Imparfait",
        "iam":"Imparfait",
        "ira":"Plus-que-parfait",
        "iras":"Plus-que-parfait",
        "íramos":"Plus-que-parfait",
        "íreis":"Plus-que-parfait",
        "iram":"Plus-que-parfait",
        "i":"Passé Simple",
        "iste":"Passé Simple",
        "iu":"Passé Simple",
        "imos":"Passé Simple",
        "istes":"Passé Simple",
        "iram":"Passé Simple",
        "irei":"Futur Simple",
        "irás":"Futur Simple",
        "irá":"Futur Simple",
        "iremos":"Futur Simple",
        "ireis":"Futur Simple",
        "irão":"Futur Simple",
        "iria":"Conditionnel Présent",
        "irias":"Conditionnel Présent",
        "iríamos":"Conditionnel Présent",
        "iríeis":"Conditionnel Présent",
        "iriam":"Conditionnel Présent",
        "a":"Subjonctif Présent",
        "as":"Subjontif Présent",
        "amos":"Subjonctif Présent",
        "ais":"Subjonctif Présent",
        "am":"Subjonctif Présent",
        "isse":"Subjonctif Imparfait",
        "isses":"Subjonctif Imparfait",
        "íssemos":"Subjonctif Imparfait",
        "ísseis":"Subjonctif Imparfait",
        "issem":"Subjonctif Imparfait",
        "ir":"Futur Simple",
        "ires":"Futur Simple",
        "irmos":"Futur Simple",
        "irdes":"Futur Simple",
        "irem":"Futur Simple",
        "indo":"Gérondif",
        "ido":"Participe"
    }


    def groupeVerbe(self,token_):
        strLemmaF = ""
        strLemmaF = token_[-2:]

        if strLemmaF == "ar":
            groupeVerbe = 1
        if strLemmaF == "er":
            groupeVerbe = 2
        if strLemmaF == "ir":
            groupeVerbe = 3
        return groupeVerbe
