# Generated by Django 4.0.4 on 2022-06-20 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('texts', '0001_initial'),
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WoLgID', models.IntegerField()),
                ('WoText', models.CharField(max_length=1000)),
                ('WoTextLC', models.CharField(max_length=1000)),
                ('WoStatus', models.IntegerField(max_length=5)),
                ('WoTranslation', models.CharField(max_length=1000)),
                ('WoRomanization', models.CharField(max_length=200)),
                ('WoSentence', models.CharField(max_length=1000)),
                ('WoCreated', models.DateField()),
                ('WoStatusChanged', models.DateField()),
                ('WoTodayScore', models.FloatField()),
                ('WoTomorrowScore', models.FloatField()),
                ('WoRandom', models.FloatField()),
                ('WoGrammar', models.CharField(max_length=1000)),
                ('WoPos', models.CharField(max_length=30)),
                ('WoLang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('WoTxt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='texts.mytexts')),
                ('WoUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.learner')),
            ],
        ),
    ]
