# Generated by Django 4.0.4 on 2022-06-20 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('texts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T2Text', models.CharField(max_length=30)),
                ('T2Comment', models.CharField(max_length=200)),
                ('TagsArchived', models.BooleanField()),
                ('TagsText', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='texts.mytexts')),
                ('TagsUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.learner')),
            ],
        ),
    ]
