# Generated by Django 4.0.4 on 2022-06-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LgName', models.CharField(max_length=40)),
                ('LgDict1URI', models.CharField(max_length=200)),
                ('LgDict2URI', models.CharField(max_length=200)),
                ('LgGoogleTranslateURI', models.CharField(max_length=200)),
                ('LgExportTemplate', models.CharField(max_length=1000)),
                ('LgTextSize', models.IntegerField()),
                ('LgRemoveSpaces', models.IntegerField()),
                ('LgRightToLeft', models.IntegerField()),
            ],
        ),
    ]
