class English:
    
    irregularnouns = ["A-G","AAPI","Ababda","abakweta","abakwetha","abas","abat-voix","abatis","abatsons","abattis","abatvoix","abatwa","Abelam","abelungu","Abenaki","Abenlen","abies","Abipón","abisetaoshi","Abitibi","Abkhaz","Abongo","Abor","aborisha","Absaroka","Absaroke","Absarokee","accused","Achang","achimenes","Acholi","ACOD","Acolapissa","Acolhua","actinomyces","actus","addax","adhisthana","Adhola","Adidas","adinkra","aditus","Adivasi","administrativia","administrivia","Adnyamathanha","aëdes","aerocraft","aeroplankton","aesthetics","æsthetics","Aeta","Afar","aflaj","Africanis","agamospecies","agbada","Aggadah","Aghorapanthi","Agta","Aheer","ahegao","ahi","Ahir","aholehole","ai","aikidoka","Aimak","Aimaq","Ainu","airborne","aircraft","aitu","ajari","akabeko","akamatsu","akanbe","akara","akeni","aktionsart","akule","akum","albatross","Albigeois","alexanders","alferes","ali'i","alikreukel","alligatorfish","allospecies","alma","almah","almeh","alms","alpaca","alumni","alumnx","amakweta","amaltas","amberfish","amigurumi","amiuchi","Amuzgo","anableps","anaphora","Anasazi","Andamanese","Andaste","anemonefish","ang moh","angelfish","anglerfish","angmoh","Angrez","angrez","ani-deshi","animanga","anime","animé","Anishinaabe","Annamese","anopheles","antelope","anti-aircraft","antiaircraft","anticommons","Anuak","API","apparatus","Appl.","Aragonese","Arapaho","arbakai","archaeoplankton","archerfish","Argobba","Aries","Arikara","arkars","Arora","Arshakuni","Arverni","ascites","Asclepiades","Ashanti","ashiko","ashipu","ashitori","ashiyu","askari","Asmat","asparagus","asperitas","Assamese","assizes","associate's","at","Atakapa","atari","ateji","Atikamekw","atomy","att","attack aircraft","attohertz","aua","aufeis","aufwuchs","Aukan","aurochs","autocannon","Auvergnese","avens","Averni","awabi","Awadhi","awara","Aymaq","Aztec","B.Cl.","B.Dr.","b/d","Babemba","babykins","bachelor's","backpackers","badlands","baht","baiji","baitfish","bajaj","Bajau","baka","Baka","Bakairi","bakkra","balaua","balian","Balinese","balloonfish","Baloch","Balti","Baluch","Bamar","Bambara","bandfish","banditti","bangamary","bangus","Baniba","Baniva","Baniwa","Banjar","bannerfish","Bannock","Bantu","Banyamulenge","baozi","Bar.","barakumin","Barakzai","barasingha","barberfish","baren","Barese","barfi","barracks","barracuda","barrelfish","basa","Basiji","bass","Basuto","bata","batchim","batfish","Baul","beachsalmon","beakfish","beardfish","Beaujolais","beaver","becak","Bedoon","beechdrops","beef","beefalo","Beijingese","bekko","bellows","beltfish","Bemba","Bena","Bengalese","Beninese","Beninois","benshi","bento","Beothuck","Beothuk","ber","berdache","berkovets","berkovetz","Berlinese","Bernese","Besisi","bessa","Betawi","BeV","beya","BGA","bhand","bharal","Bhutanese","Bhutani","bi","bianzhong","bibble","biceps","Bicolano","Bidoon","bifteki","Bigfoot","Biles","billfish","Binzuonese","biofacies","bioseries","biospecies","biotherapeutics","Birmese","biscotti","bison","bitchtits","bitchy-pants","bitchypants","bitcoin","bitters","biwa","blackbuck","blackfish","Blackfoot","blackgame","bleachworks","bleak","blewits","blindfish","blini","blobfish","bloubok","blowfish","bluecurls","bluefish","blues","Bn.","boar","boarfish","bob","bocaccio","Bodo","boerewors","boggards","bojagi","bokken","bokonon","bolas","bolekaja","Bolognese","bonefish","bonenkai","bonito","bonsai","bonsho","bonshō","bontebuck","boomslang","Bordeaux","bordeaux","Bordelese","Borg","Bornouese","Bornuese","borzoi","boschbok","bossy-pants","bossyboots","Bostonese","botamochi","both-hands","bottlefish","bottomfish","boulti","bourgeois","boxfish","Bozo","BPM","bpm","Bps","brahmana","branks","brant","brassworks","breadfruit","break-bones","bream","Bribri","brickworks","bridi","brigalow","briglow","brill","brinkmate","brisling","bristletail","brit","brivla","broccoli","brocoli","broodfish","Brulé","Brussels","Btb.","buchikamashi","budju","buffalo","buffalypso","Buffalypso","bugfish","bukkumi","bulerias","bun","Bungay","Bungee","Bungi","Bungie","Bungy","burakumin","burfee","burfi","burfish","burgeois","burikko","Burkinese","Burmese","burrfish","bushbuck","butchers","butsudan","butterfingers","butterfish","butterflyfish","Bwiti","C.Bon.","C.Bssn.","cactus","Caddo","Cahita","Cahuilla","calmecac","calpolli","Camaldolese","camas","cancrizans","candirú","candlefish","Cannois","cannoli","cannon","Cantonese","capelin","carbonari","cardinalfish","Carib","cariboo","caribou","carideer","caries","carp","carrots","cash","Cashibo","catalo","catànies","Catawba","catchpoints","catfish","cathair","cattelo","cattlehead","cavefish","Cayuga","ccf","CCF","Ccf","CDS","ceiba","cenospecies","census","cent","centistokes","cestus","cevapi","Ceylonese","cha","Chablis","chablis","chabudai","Chackchiuma","chad","chainworks","Chakma","challan","Chamicuro","chamoe","chamois","champers","changseung","changshan","changsung","chaqu","char","Charan","Charedi","charr","Chartreux","chashitsu","chassis","châssis","Chatino","Chaurasia","chawan","cheetal","cheetul","chek","Chekiangese","chengyu","cheongsam","cherubin","chesthair","Chewa","Cheyenne","Chibcha","Chickasaw","chickenlips","chigetai","chikan","chikuwa","Chilcotin","Chilula","chinafish","chindi","Chinese","chipekwe","Chipewyan","Chippewa","chips","Chiricahua","chirori","chital","Chitpavan","Chitpawan","Chleuh","chochem","Choctaw","chogori","choka","choko","chon","chongake","chonmage","chordopox","chotki","chowtal","chromis","chronospecies","chub","chuchvara","Chud","Chude","Chukchi","Chumash","chupacabras","Chuukese","cigarfish","cinclodes","Cingalese","Cinghalese","cissus","civics","Clallam","classifieds","Clatsop","cleanerfish","clematis","cleverclogs","cleversticks","clingfish","cloth-ears","clownfish","cM","cmavo","cmene","coalfish","coalworks","cobblerfish","cobia","Cocama","Cochin-Chinese","cockfish","Cocopah","cod","codfish","coenospecies","cofferfish","Colemanballs","coli","colluvies","colugo","combfish","comitatus","comitia","commis","Con.Bn.","conatus","Conchese","condemned","condor","Conestoga","confectioner's","congeries","Congolese","conspecies","constaff","contrapposto","contretemps","copperworks","coralfish","corbita","cordyceps","cornetfish","corps","corydoras","cosmos","coss","coulis","countryfolk","Coushatta","cowfish","Cowichan","coypu","cpmm","cpp","cps","crabfish","craft","cran","crappie","crawfish","crawlfish","crayfish","Cree","creekfish","crestfish","Crnt.","Cro-Magnon","Croatan","crocus","croquis","crossfish","Crow","CROWS","cuapao","cucumberfish","cultispecies","Cumanagoto","cun","Cuna","cunjevoi","cunji","curryfish","cursus","customs","cutlassfish","Cutsahnim","cuttlefish","cwt","cwt.","cyberpolitics","cyclops","cyphonautes","cypris","cytospecies","dace","daddikins","daddy-long-legs","daddy-longlegs","daddykins","Dai","daifuku","daigappei","daikon","daikyu","daimio","daimyo","Dakarois","dakimakura","dakuten","dala","dalasi","damma","damselfish","dan","dango","danpatsushiki","dantian","danwei","daotai","dartfish","daruan","Dayak","dazibao","dealfish","débris","Deccani","deceased","decubitus","dedans","deekies","deeksies","deer","deg.","degeiko","demicannon","Dena'ina","dengbej","deni","deshi","detritus","Deutschmark","devilfish","dhole","dhufish","dialetheia","dice","dihu","dilawan","Dilazak","dillseed","Dilzak","ding","dinges","Dionysia","diplomatics","Ditidaht","Dives","Djuka","docklands","doctorfish","docuseries","dodoitsu","dogfish","dohyo","dohyo-iri","dojikko","dojo","dokda","dollarfish","dolphinfish","donabe","dong","dongba","Dongxiang","dotaku","doujin","doujinshi","downstairs","doz","doz.","dozen","draatsi","dragonborn","dragonfish","dreads","dreamfish","driftfish","drow","Drukpa","drumfish","Druze","duckweed","ductus","dudou","duergar","dumbek","Dusun","duxelles","Dyak","dyeworks","dystopia","e-series","E.H.","eboshi","ecchi","ecospecies","Edinbourgeois","Efik","Egbo","eightsies","EJK","Ekpe","Eldar","elect","electronics","elephantfish","elevenses","elk","Elunchun","ema","emaki","embarras","emoji","emu","enamelworks","engawa","English","enkai","enlightened","enokidake","enokitake","entremets","entrepas","epacris","Eph.","ephialtes","ePrix","epsilontics","erhu","ermine","ernai","eroge","erxian","Eskimau","Eskimo","esthetics","eta","ethelborn","ether","Ether","ethics","ethnie","ethnospecies","ethospecies","eugaree","eugarie","euro","Euro","Euroyen","eusperm","eV","Evenk","exahertz","exclus","excursus","exonumia","EXP","extrados","ezafe","Ezhava","fa'afafine","facies","Faeroese","Færoese","fair","fairgrounds","fakelaki","Fakémon","falafel","fallen","fallfish","falls","fALS","fancypants","fanfish","fapiao","fario","farmerfish","Faroese","Faroish","fash","fatele","fatherkins","fava","Faverolles","fedai","fellagha","Fellatah","femina","Ferrarese","fig.","filefish","fils","finfish","finoki","finsko","firangi","Firangi","firefish","firstborn","fish","fishworks","fivesies","Fl.","flashlightfish","flatfish","flathead","flatlands","flexus","flightcraft","flounder","fluctus","flycraft","flyfish","flyingfish","flyspeck","fmol","fmz","fokonolona","fokontany","folk","fonds","Foochownese","foolfish","foraminifera","forceps","Foulah","four-eyes","fourses","foursies","fowl","foxfish","FPS","fracas","FRAN","Frankenfish","frankenfish","Fransaskois","Freikorps","French","frogfish","frosh","frostfish","ft","fu","fudanshi","Führer","fu'ivla","Fujianese","fujoshi","Fukien","Fukienese","fukusa","Fula","fullam","fumblefingers","fumidashi","fundoshi","Fur","furigana","furisode","furo","furoshiki","fusen","fusensho","fusilli","fustilugs","fusuma","futanari","futures","Fuzhounese","fuzznuts","Gabonese","gachapon","gadje","gaiji","gaijin","Gaika","gaiwan","gaje","gaku-ran","gal","galge","galloglass","gallowglass","gallows","Gallurese","gamaka","gamefish","gamefowl","Ganda","ganglioseries","Ganguela","gaokao","gapik","gardebras","garfish","garnets","garnetz","Garo","garpike","gashapon","gasshohineri","gastraea","gastrea","gasworks","gaur","gauss","gayageum","gaywings","gazelle","Gbps","Geechee","Geechie","Geechy","geisha","gelati","gemfish","gemmen","gemsbok","geneat","Genevese","genkan","Genoese","genomospecies","genospecies","genro","Gentlemen","gentlemen's","Gentlemen's","Gents","gents'","gershayim","geta","Gg","gharial","ghostfish","ghoti","gi","gibfish","giboshi","gig","gigabaud","gigagauss","gigahertz","Gilbertese","Gilyak","giraffe","girsh","gisaeng","gismu","Gitksan","Gitxsan","glacis","glans","glassfish","glassworks","globefish","GMO","Gnawa","gnocchi","gnu","gnudi","Goanese","goatfish","goban","goby","goji","goldeye","goldfish","Goldfish","goldilocks","goldylocks","gonja","gonoforceps","goody-two-shoes","goosefish","gopik","govi","GP","GPM","graben","graffiti","gramps","grams","grand","grand rounds","grapefruit","grapeshot","grapevine","grawlix","grayling","greedyguts","greenfish","greenfly","Grenzer","grice","gridlers","Griqua","gris-gris","gross","grounds","grouper","grouse","grumpy-pants","grumpypants","gtt","Guale","Guangzhouese","gubbins","Guianese","guineafowl","guitarfish","gukja","gulden","Gullah","gumiho","gunbai","gunworks","guotie","guqin","Gurkha","gurnard","Guyanese","guz","gweilo","gyapik","gyaru-moji","gyarumoji","gyoji","gyoza","gyros","habal-habal","haddock","Hadendoa","Hadendowa","hadith","Hadjemi","haegeum","hagfish","haibun","haikai","haiku","hairyfish","Hajjam","haka","hakama","hake","hakurei","hala","half-fish","halibut","halitus","hamachi","hames","hanamachi","hanazumo","hanbok","handakuten","handfish","Handstein","hangi","hangiri","haniwa","hanja","hanzi","Hanzi","hao","hào","haole","haori","ha'p'orth","hapuku","hapuʻu","haramaki","Harari","haras","Haratin","hardihead","hardyhead","Haredi","Hareidi","haridashi","harigata","harimanage","hartebeest","harvestfish","hasanat","hatakikomi","hatchetfish","hatfish","Haunebu","hautbois","hautpas","Hawara","Hawiya","Hawiye","hawkfish","Hazara","hazardise","hazardize","h'dq'rs","hdqrs","hdqrs.","head","headfish","headquarters","heads-up","headworks","healsfang","heathen","heiau","heikegani","heiti","helles","hellspawn","henfish","hengeyokai","hentai","hentaigana","heqat","Herero","hermeneutics","herring","hertz","heya","heyagashira","hiatus","hibachi","hibakusha","Hidatsa","hidoku","hifu","higashi","higonokami","hikikomori","hikiotoshi","hikkake","Hiligaynon","hinoki","hippopotamus","hiragana","hirola","Hitchiti","Hiwi","Hn.","Ho-Chunk","hogfish","hoki","hokku","holibut","hongbao","Hongkongese","hongweibing","Hoo-Hoo","Hopi","Horlicks","hornfels","hornfish","Horowitz","hors-d'oeuvre","hors-d'œuvre","horsefish","horsepower","hosho","hosomaki","hotchiku","houndfish","housestaff","houting","Hova","hovercraft","HSTS","Hualapai","Huaorani","hubs","huia","hukou","hundredweight","Hunkpapa","Hupa","hupia","huqin","Huron","hustings","hutong","Hutu","hutung","huwasi","hwan","hyæna","hyena","hyoshigi","I-Kiribati","Iban","ibex","ibis","icefish","ichimon","ichnofacies","ichnospecies","ichomage","ictus","ides","Ides","Igbo","Igorot","Ijaw","ikupasuy","ilish","Illinois","imagawayaki","immunospecies","imp.","impala","impatiens","impimpi","in","Inca","inclus","infauna","infraspecies","Ingush","Inka","inkfish","innings","inro","insignia","intai-zumo","intrados","inugami","inuhariko","Inuit","iomante","ionocraft","IOPS","IPR","iPSC","ipu","Iqalungmiut","iraimbilanja","Irakw","Iraqw","iriambilanja","iris","Irish","ironworks","Iroquois","irori","Irula","isamiashi","Isoko","Issa","issei","isu","Ivatan","iwi","iyomante","izakaya","izori","ja","jab molassie","jackfish","jackfruit","jacksnipe","jacques","jamo","jangseung","Japanese","Japayuki-san","Jarai","Jat","Javanese","javelinfish","jawfish","Jedi","jelly-fish","jellyfish","jellyplankton","jeon","jew-fish","jewelfish","jewfish","jianbing","jiangshi","jiao","jiaozi","Jicaque","Jigglypuff","jin","jincan","jinghu","jinja","jinn","jinriki","jisei","jo","jobfish","Jollof","Jolof","jomo","jonokuchi","Jopadhola","judgy-pants","judogi","judoka","jugaad","jugfish","juglans","juhyo","juhyou","juku","jukujikun","jun","jun-yusho","junglefowl","jungyo","Jurchen","juryo-kaku","jus","justacorps","Kabardin","kabloona","kabocha","kabosu","kabosy","Kabulese","kabuto","Kadazan","kadogo","kadomatsu","kahili","kahuna","kaibun","kaiju","kainahineri","Kaingang","kaiseki","kaj","kakahi","kakaho","kakanin","kakawin","kakemono","kakenage","kakezori","Kalenjin","Kalinago","Kalwar","kama","kamaboko","kamado","kamaitachi","Kamas","Kamboh","Kamboj","kamees","kami","kamokamo","kamuy","kan","kana","Kanak","kango","kanji","Kankanaey","Kankanay","kanreki","kanto-sho","kanzashi","kaomoji","kapu","Karaim","karajishi","karanteen","karateka","karayuki-san","karbovanets","kardiya","karesansui","Karluk","Karok","Karuk","kasuyu","kata","katakana","katana","kataribe","katashiro","katasukashi","katauta","kaumatua","kawachibuna","kawazugake","Kayah","Kayin","kB/s","kbp","kbps","kBps","kc/s","Kebecois","kehua","keikogi","keiretsu","kekaeshi","Kelabit","kelpfish","kelvin","kemonomimi","ken","kendhang","kendi","kendoka","kereru","keris","kermes","kesa","kesho-mawashi","Ket","ketaguri","KeV","kgal","Khalifa","Khalkha","khamaseen","khanith","Kharia","Khasi","Khattak","Khazar","Khmer","Khoekhoe","Khoikhoi","Khoisan","khoums","Khukhrain","khur","kiasi","kiasu","kibei","kibinago","Kickapoo","kickshaws","kigaku","kigo","kikumon","Kikuyu","kikwembe","Kiliwa","killdeer","killifish","kilobaud","kilocal","kilohertz","kilolambda","kilolux","kimarite","kimarite-gakari","kimedashi","kimetaoshi","kimono","kin","kina","kinchaku","kingfish","kinjite","Kinmenese","Kinois","kiore","Kiowa","kip","kipuka","Kirghiz","kirikaeshi","kirimon","kisaeng","Kitasoo","Kitchawan","kite","kitsune","kittiwake","kiwi","kiyomi","kkoktu","kkwaenggwari","klackers","Klallam","Klamath","klar","km/hr","kmph","knifefish","knot","knucklenuts","ko","koa","koaro","Koasati","koauau","kob","kobo","kobyz","kodachi","kofun","koi","koinobori","kokeshi","kokopu","koku","kokuji","kolbasi","kolbassi","kolbasy","komainu","komatasukui","komboskini","Komi","kominkan","komku","komusubi","konbini","koneke","Kongolese","kongsi","Konkani","koorhaan","korhaan","Koriak","korokke","korovai","Korowai","KORT","koru","Koryak","koseki","Koshare","koshikudake","koshinage","koss","kotatsu","kotehineri","kotenage","Koyukon","Kpelle","kph","kpm","krama","krill","kroepoek","kroo","krotovina","kuai","kubihineri","kubinage","kudu","kumara","Kuna","kunai","kupuna","kuromaku","kurus","kusarigama","kushtaka","Kuvasz","kwacha","kwai","kwailo","Kwakiutl","Kwakwaka'wakw","kya","kyabakura","kyat","kyodai","Kyrghyz","Kyrgyz","laari","Lacandon","laceworks","ladyfish","lagatoi","lakatoi","Lakota","lamassu","lamba","laminak","lampfish","lancefish","lancers","lancetfish","landfowl","lanternfish","Lao","laowai","laplas","Lapp","lapsus","lari","lates","lavalava","lazybones","leadworks","leaffish","leatherworks","Lebanese","lebkuchen","lechon","lechwe","lede","leed","leerfish","Lega","lek","Lenape","lens","lenticularis","leod","lexicosemantics","leyak","Lhoba","Lhotsampa","Lhotshampa","li","liang","liangpi","lichen","Lillooet","Limbu","limeraiku","limeworks","ling","lingcod","links","lionfish","lipa","Lipan","lishenets","listeria","Lisu","lithofacies","lithops","litotes","lizard-folk","lizardfish","lizardfolk","loa","logperch","logseries","Lohana","longlegs","longshanks","Longuda","Longueuillois","longyi","lontar","loomworks","looney-tunes","louis","louis-d'or","Löwchen","luau","Lucchese","lujvo","luma","Lumbee","lumpenbourgeois","lumpfish","lumpia","luna","lungfish","Luritja","lutefish","lux","lwa","lwei","lykoi","lynx","Lyonese","M.Eng.","Macanese","Macaoese","Maccies","Machiguenga","machinima","mackerel","macrolichen","macrospecies","madda","madrona","madrone","madroño","Maedi","maegashira","maezumo","magatama","Magyarab","Mahar","mahboob","mahbub","mahi-mahi","mahimahi","Mahorais","Mahori","Maidu","maiko","mains","Majlis","majlis","Makah","maki","makimono","makiotoshi","makisu","makunouchi","makuuchi-kaku","mala","Malagasy","Malecite","Maliseet","mallard","malleefowl","Maltese","mamarazzi","Mambila","mampoer","Mamprusi","mamudi","mamushi","manageableness","Manahoac","manat","manatee","mandarinfish","mandazi","Mandinka","manefish","manga","mangaka","manhwa","manini","maniplies","Mansi","manti","mantou","manus","Manx","man'yōgana","manyplies","Maohi","maoli","Maoli","maomao","Maori","Māori","Maouri","Mapuche","Marans","Marathi","marblefish","Maricopa","mariengroschen","marlin","Marmorkrebs","marmorkrebs","marquis","Marseillais","Marshallese","Martiniquais","Marwari","mas","Mashpee","mashrabiyya","maskinonge","master's","masters","Masters","masu","Mataco","matai","matatu","mathemaku","matsuri","mawashi","maxiseries","Maya","mayfish","Mazahua","Mazatec","mbari","Mbps","MBps","mbsf","mc","McDonald's","mcm","means","measles","meatus","meatworks","mecha","media","medusafish","meeple","meg","megabaud","megafauna","megafish","megaflops","megaflora","megagauss","megahertz","meganekko","megaplankton","megasiemens","megatsunami","Meherrin","meibutsu","meido","meishi","mejlis","Mejlis","Melanau","mele","melidectes","Menangkabau","Menehune","menhadden","menhaden","Menominee","Menomini","menpo","Mentawai","menuki","mephato","Mercedes","mereswine","Merina","meroplankton","merswine","Merveilleux","meshrep","Meskwaki","mesoplankton","metalworks","metaphysics","metaseries","metazooplankton","Metis","metis","metsubushi","mews","Mewuk","Mexica","mi/hr","Miami","Miccosukee","michiyuki","mici","Micmac","microfacies","microforceps","microgauss","microGauss","microhertz","microJy","microlux","micronekton","microsec","microsiemens","microspecies","microswine","miesies","Mihanere","Mikmak","Mikmaq","miko","mikoshi","Milanese","military","milkfish","mill","milligauss","millihertz","millilux","millionfish","milliroentgen","millisiemens","millistokes","millreis","milreis","Minang","Minangkabau","minenwerfer","minga","Miniconjou","miniseries","mink","Minnetaree","mino","minshuku","Mirandese","mirepoix","Miri","misbegotten","miscellanea","miseryguts","Mishing","Mishmee","Mishmi","Miskito","Mississauga","mithai","mititei","mitochondria","mitsumata","Miwok","Miwuk","Mixtec","miya","Miyana","Mizo","mizuhiki-maku","mM","moai","MOC","Moche","mochi","Modenese","Modoc","Mohegan","Mohmand","mo'i","mojari","moka","Moken","Moki","moki","mokihi","momme","mommykins","moms","moneybags","möngö","monkfish","monkfruit","monme","mono-ii","Monpa","month","monyplies","moochin","mooi-jai","moonfish","moorfowl","moose","Moqui","moran","morgen","Moriori","morwong","mosquitofish","motherkins","Motilon","motlopi","MOTOS","MOTSS","mousedeer","mousseux","Mowree","Mpangwe","MPG","Mpongwe","MSM","MSSC","mu","muang","mudalia","mudansha","mudfish","mueang","Muisca","mujina","muke","Mulao","mullet","Multnomah","mumble-matins","mumian","mummykins","Munda","Mundugumor","muqarnas","Muscogee","muskellunge","Muskhogee","Muskogee","musubi","muttonfish","mv","mwchin","mxn","Mya","mya","Myanmarese","mycoplankton","myoseki","mythopoetics","nagaimo","nagamaki","nage-waza","nagewaza","Nago","naira","nakfa","nakodo","namahage","namaycush","Namboothiri","Nambudiri","Nampoothiri","Nampootiri","nannoplankton","nanogauss","nanoHertz","nanohertz","nanori","nanosiemens","nanozooplankton","Nanticoke","narcobourgeois","narrows","narwhal","nase","nasnas","Natchez","naupaka","Navajo","Na'vi","Nawar","naxar","Nazgul","Nazgûl","nB","Ndembu","Ndyuka","neat","nebari","needlefish","Negretti","Negrito","nekomimi","nene","Nenets","neospecies","Nepalese","Nepaulese","nephros","netherhose","Nethinim","netsuke","neuroglia","newborn","nexus","Ngarrindjeri","Ngbandi","Ngoni","Ngqika","ngwee","Ni-Van","ni-Van","ni-Vanuatu","Ni-Vanuatu","nibs","nichonage","nicker","nien-hao","Nigerois","nigger-fish","niggerfish","niggerlips","nigorobuna","Nihang","nikkei","nikkeijin","nikuman","nilgai","nilgau","nilghai","nilghau","nimaigeri","nimble-chops","nine-eyes","ninesies","Ningbonese","ninja","Nipissing","Nipmuc","Nipmuck","Nipponese","Nisei","nisei","Nisenan","nishi","Niskwalli","Nisqualli","Nisqually","Nivkh","No","Noah's","nobori","nodachi","Nogai","nohkan","nolt","nomikai","nomothetics","noncompos","nonelect","nones","nonfish","nonictus","noodlefish","Nootka","nopal","Norridgewock","Nosferatu","nosferatu","noshi","not.","nothospecies","Nottoway","nox","NTU","Nueir","Nuer","numbfish","numbnuts","Nunamiut","Nunavimmiut","Nuorese","nuqta","nureongi","nurseryfish","nutukas","nylgau","nylghau","NZ","Nzema","Nzima","o-mikuji","oarfish","Ob.","obake","obi","obijime","obv.","odachi","odango","offspring","ofuda","ofuro","Ogoni","Ohlone","ohu","oichomage","oilfish","oilworks","oiran","OIS","Ojibwe","okiya","okonomiyaki","okta","okuriashi","okuridashi","okurigake","okurigana","okurihikiotoshi","okurinage","okuritaoshi","okuritsuridashi","okuritsuriotoshi","Olds","oligodendroglia","olisbos","Ologun","Omaha","omake","omata","ombuds","omics","omikuji","omiyage","omnishambles","ondol","Oneida","onesies","oni","onigiri","onnagata","Onondaga","onsen","Ontos","oodachi","O'odham","oops","Oorlam","oospecies","opah","opakapaka","opanak","opara","opia","orca","öre","Orleans","Oroch","Oromo","Oropom","Oroqen","Orthodox","oryx","Osage","osakate","oshibori","oshidashi","oshitaoshi","osotogari","otaku","otakukin","otherkin","Otherkin","Otomi","out-of-bounds","Outagami","oxea","oyabun","oyrur","oz","oz.","ozeki","PACS","Padaung","paddlefish","Padouca","Pahari","paintworks","pair","Paiute","Paiwan","pajeon","pakeha","pakirikiri","palaeospecies","palaeosubspecies","palagi","Palawala","paleofish","pampas","panfish","panzarotti","panzerotti","paopao","Papago","papalagi","paperworks","paradisefish","parados","parajudoka","parasang","parasitofauna","parasperm","pardessus","parley-vous","parr","parrotfish","partridge","pas","pas-de-deux","pasalubong","Pasifika","Passamaquoddy","pastizzi","patois","patupaiarehe","patutuki","paua","Pawnee","pax","payara","paʻanga","Pbps","pct","pearlfish","pedaheh","pedanda","pee","Pekinese","Pekingese","Pekingnese","peled","peltops","pencilfish","penfish","pennorth","pentas","Peoria","pepperoni","Pequod","Pequot","percent","perch","permille","permit","pers.","petahertz","petroyuan","pettichaps","pettychaps","pfeffernusse","phage","phalaris","phenomenon","phenospecies","Phillips","phlox","phoenix","phosphospecies","phragmites","phylospecies","pice","pici","pickerel","picosiemens","pie","Piedmontese","pierogi","pigfish","pihoihoi","Pikachu","pike-perch","pikeperch","pilchard","pili","pilotfish","pils","Pima","pince-nez","pineapplefish","pinfish","Pintado","Pintupi","pipefish","pipetongs","pipfruit","piranha","piroghi","piroschki","piroshki","pirozhki","Pisces","pisspants","Pitiguara","pixiu","plaice","plankton","plantkin","platy","platyfish","pleasurecraft","plexus","ploughman's","plover","plumbata","plunderfish","pluries","ply","POAO","Pocasset","poeticks","poetics","poghaden","pohutukawa","poi","Pokanoket","Pokéman","Pokemon","Pokémon","Pokot","politics","pollack","pollock","pomfret","Ponca","pondfish","ponyfish","poolfish","poomsae","poomse","porcini","porcupinefish","porkfish","Portuguese","Portugueze","postiche","Potawatomi","Potiguara","potjiekos","potworks","Powhatan","ppb","PPM","ppt","præs.","prawn","precis","précis","prefrosh","pricklefish","printworks","pro-sumti","processus","proggins","pronghorn","prophases","prospectus","protospecies","prowfish","psc","pseudo-haiku","pseudohaiku","pseudoplankton","pseudospecies","psoas","psy-ops","psyops","ptarmigan","PUBS","pudu","pufferfish","puits","pukao","pukeko","pūkeko","pul","Puli","pumsae","pumse","pun","punalua","pupfish","puputan","pussums","Putinversteher","puto","putois","Puyallup","qapik","Qarluk","Qarluq","qepik","qing","qirsh","qite","qobyz","Quadi","quadragesimalia","quadriceps","quail","Quanzhounese","Quapaw","quasispecies","Quebecois","Québecois","Québécois","Quechua","queenfish","quenk","quid","quillfish","quinnat","Quioucohanock","Quiyoughcohannock","qursh","rabbitfish","rackabones","rafsi","ragfish","raggare","Rahanwin","rai","railworks","rainbowfish","raindeer","raiyat","rand","Rand","Rangoonese","Ranquel","Rapanui","rape","rapier-fish","rappen","ratfish","rattlewings","rax","razorfish","recal","redbait","redfish","reedbuck","reedfish","Reichskanzler","reimiro","reindeer","relais","religieux","religious","remora","rendevous","rendezvous","renga","renminbi","revers","rhinoceros","Rhodesli","rhomboides","rhubarb","ribbonfish","ribospecies","ricefish","rictus","rikishi","rimu","rin","ringgit","ringtail","rio","rivercraft","Rivesaltes","riyo","roach","robata","robofish","rockfish","roe","roedeer","Roget's","roji","rokurokubi","Rolls","Romani","Romanichal","Romany","Rommany","Romnichal","romusha","rōmusha","ronin","roosterfish","ropefish","rosefish","rothe","rotini","rotorcraft","roundfish","Rouran","roux","RPS","rudd","rudderfish","rugelach","Rungu","rupchanda","Rus","Russ","Rutul","Rwandese","ryokan","ryotei","ryuteki","ryūteki","Saami","saamlaw","Saanich","sabamiki","sablefish","sabrefish","Sac","sac-a-lait","saccharomyces","sagemono","Sahaptin","Saho","sai","Saigonese","saiko-komon","sailcraft","sailfish","sailor's-choice","sails","Saint-Dominguois","Sais","Saka","Sakai","sakatottari","sakazuki","salamanderfish","Salinan","salmon","sALS","saltus","saltworks","Samburu","Sami","Sámi","samisen","samlor","Sammarinese","Samoyed","samsonfish","samurai","sandfish","sandgrouse","sangza","sanies","sanmai","sansei","sansho","Santal","Santee","Santhal","santoku","sanyaku","saofai","saola","sapiens","sapiutan","sardinella","sarubobo","sasaeng","satang","Satmar","Satnami","satoshi","satoyama","satyagrahi","saucercraft","Sauk","Saurashtra","Sauternes","sawbones","sawfish","Sax.","scabbardfish","scad","scaldfish","scalefish","scampi","scandicus","scatterbrains","scaup","scfs","schizopolitics","schrod","schwartza","scissars","scissors","scops","scorpionfish","Scottish","scoutcraft","scrobic","scrubfowl","scup","scuttlefish","seabass","seabream","seacraft","seafish","seafowl","seaperch","searuffe","seatrout","sec","secesh","Secotan","Secwepemc","sedoka","seecatchie","Seelie","seerfish","seifuku","seinen","seirfish","seiyuu","sekitori","sekiwake","selbri","Selkup","selma'o","semantics","seme","semese","semi-works","Seminole","semispecies","semiworks","sen","Seneca","Senegalese","Senoi","Senoufo","senryu","senryū","sensei","senshuraku","sentai","senti","Sentinelese","Senufo","Senussi","seppuku","Serer","Seri","series","Sesotho","sevensies","Seychellois","shabiha","shad","shahi","shahtoosh","shahtush","shaken","shaku","shambles","shamisen","shamoji","shampers","Shan","Shanghainese","Shantungese","shaobing","shaomai","shari","Shasta","shatei","shatoosh","Shawnee","She","she-walrus","sheatfish","sheefish","sheep","sheepe","sheepshead","sheftalia","sheldduck","shelduck","shellfish","shengnu","shengnü","Sherpa","shetani","shido","shifu","shigella","Shih Tzu","shihon-bashira","shiitake","shikigami","shiko","Shikoku","shikoku","shikona","shilingi","shimeji","shimekomi","shimewaza","shindeshi","shini-tai","shinigami","shinjitai","shinkansen","Shinnecock","shinobi","shinrimei","shintiyan","shintyan","shirataki","shishamo","shisho","shit-for-brains","shitake","shitatedashinage","shitatehineri","shitatenage","shitnuts","shizoku","shochikubai","shōchikubai","shogun","shoji","shokkiri","shokunin","shorefish","shotai","shovelfish","shozoku","shrimp","shrimpfish","Shuar","shubunkin","Shughni","shukun-sho","shumai","shumokuzori","shuriken","Shuswap","shuttlecraft","shvartze","siafu","siamang","Siamese","sidhe","siemens","Sienese","sifu","sika","Sikkimese","silkworks","sillykins","silverfish","silversides","Singalese","Sinhalese","sinik","Sinixt","siopao","sixies","skatefish","skeesicks","skeezicks","Skidi","skiffer","skilfish","skipjack","skull-and-crossbones","skullfish","skunkworks","slph","sly-boots","slyboots","smallcraft","smartypants","snailfish","snakefish","Snickers","snipe","snipefish","snookums","snuffers","soapfish","soapworks","sobersides","sockeye","softworks","soi","sokaiya","sokubiotoshi","sokushinbutsu","Solano","soldierfish","Somal","somoni","Songhai","Songhay","songthaeo","sonkyo","sonnikins","sonnykins","Sonrai","sorites","sotogake","sotokomata","sotomuso","sototasukizori","Sourashtra","sous","spacecraft","spacekin","spadefish","Spanish","sparks","spätzli","spawn","spearfish","species","speculaas","speculoos","Speedos","sperm","Sphynx","spiall","spikefish","spindlelegs","spindleshanks","spiritus","spookfish","sporopollen","sportfish","spotfin","spoutfish","sprat","springbok","springfish","spruce","squaretoes","squash","squawfish","squid","squint-a-pipes","squirefish","squirrelfish","srang","stadia","staff","stapes","starcraft","starfish","Stasi","statisticks","status","steakfish","steelhead","steelworks","steenbok","steenbras","steinbok","steinstrasse","Stillsons","stingfish","stockfish","stokes","stone","stonebuck","stonefish","streamworks","Strelitz","striped-pants","studfish","sturgeon","stygofauna","stylops","subfonds","subseries","subspecies","subsubseries","subtribus","suckerfish","sudachi","Sudanese","sugartits","sukuinage","sukuk","Sukuma","Sulu","Sumbanese","sumo","sumotori","sumti","sumu","sun","sunami","Sundanese","sunfish","sunperch","Sunyavadi","superfecundity","superficies","superseries","superspecies","suppli","supplì","surgeonfish","surimono","Surinamese","sushiya","susoharai","susotori","Susquehannock","swai","swallowfish","swan","Swati","Swazi","sweepstakes","sweetcheeks","sweetfish","sweetlips","sweets","sweetums","swellfish","swine","Swiss","swordfish","SXS","Székely","tabes","tabi","tachi","tafsir","Tagalog","Tagbanua","Tagbanwa","tagetes","Tai","Taino","tais","Taishanese","Taiwanese","taiyaki","taklu","takoyaki","tales","Taliban","Talysh","tamaraw","tambon","tampan","Tanaina","tangare","tangbao","tangyuan","taniwha","tankobon","tanooki","tanru","tansu","tanuki","taonga","taotai","taotie","taphofacies","taraiu","Tareen","tarpon","tarwhine","tasukizori","Tat","tatami","tategyoji","tatsama","Tattersalls","tawaif","tawara","Tbn.","Tbps","tbs","tcf","tein","tej","tekkers","telescopefish","teleseries","teletsunami","telpochcalli","Telugu","tench","tenge","tengu","tennesi","tenno-hai","tensies","tenuki","teppan","teppo","terabaud","terahertz","Terocodame","tesla","Tetela","Teton","tetri","Tets","teuchi-shiki","Tewa","Thai","Thao","thaumarchaea","thebe","Thembu","Thimbu","thokcha","thornfish","thou","thousand-legs","threadfin","threadfish","three-lips","threesies","thrillcraft","thrips","thumbikins","thumbs-down","thumbs-up","thunderfish","tiang","tidytips","Tiele","tifaifai","tifosi","tigerfish","tikanga","tilapia","tilefish","tileworks","Tillamook","timarau","timber-toes","Timbisha","timeseries","tinfish","tinsnips","tinworks","titoki","tivaevae","tivaivai","tiyin","tiyn","tlaquimilolli","Tlingit","Tmbn.","toadfish","toddlekins","toea","togemans","Togolese","togue","tokei-gakari","tokkuri","tokkurinage","tokonoma","tokoyama","Tolai","Tolowa","Toltec","tomcod","tomoe","tonfa","tongkonan","tonguefish","Tongva","tongzhi","tonya","toothfish","toots","topi","Toraja","torii","torikumi","torikumi-hyo","torinaoshi","toro","torr","torrentfish","toshiyori","toshiyori-kabu","totoaba","Totonac","tottari","tournedos","tra","transseries","transwomyn","travois","Trb.","treefish","TrEPS","Trgl.","tribus","triceps","triggerfish","triskeles","trivia","triviata","Trokosi","trokosi","trophospecies","trout","trufax","trugg","Trukese","trumpetfish","trunkfish","truscum","tryworks","tsampoy","tsetse","tsuba","tsubo","tsuchinoko","tsukaminage","tsukebito","tsukidashi","tsukiotoshi","tsukitaoshi","tsukite","tsukubai","tsumatori","tsun","tsuna","tsunami","tsundere","tsuridashi","tsuridono","tsuriotoshi","tsutaezori","tsuyuharai","Tuareg","tuatara","Tuba","Tübatulabal","tubestock","tubfish","tuchun","tui","Tujia","tukutuku","tuladi","tulou","Tumbuka","tuna","tunnyfish","Tupperware","tupperware","turbot","Turinese","turkeyfish","Turkmen","turuq","Tuscarora","tuskfish","Tutsi","twelvesies","twinkletoes","twosies","tychoplankton","tyiyn","Tyrolese","tyyn","tzimmes","UAS","ubume","Ubykh","Uchee","uchi-deshi","uchiage","uchigake","uchigatana","uchikake","uchimuso","Uda","Udasi","Udmurt","udon","ugari","uguisubari","Uighur","uji","uke","ukiyo-e","ukiyoe","ukiyoé","ukiyoye","UKP","ume","Unalachtigo","uncs","underprivileged","undersigned","undertaker's","unicornfish","unseelie","Unseelie","unzoki","Upsaroka","upshorts","upstairs","uramaki","Urhobo","uro","Uro","Uru","urushiye","ushioni","ushiromotare","uta","utchari","utopia","uwatedashinage","uwatehineri","uwatenage","Uyghur","Uygur","Va.","VAC","vatu","Vaudois","VDC","Veepstakes","veepstakes","veg","veldtschoen","veldtschoon","velvetfish","vendace","venturi","vermin","vetkoek","Viennese","Vietcong","Vietnamese","viperfish","virginal","virginalls","virginals","virioplankton","vis-a-vis","vis-à-vis","Vl.","Vla.","Vlach","Vn.","voc.","vol-au-vent","Vopo","VPSO","wa","waa","wagashi","wagonworks","wagyu","waiata","waifu","wairua","waitoreke","waka","wakashu","wakizashi","walleye","wallfish","walrus","Wampanoag","wampum","wananga","Wanapum","wanga","wapanese","Wapanese","wapiti","warcraft","wardcorps","warehou","warez","waridashi","Warli","waryfish","washitsu","wasla","waspfish","watashikomi","watchmaker's","water-bellows","waterbuck","watercraft","waterfowl","watersheep","Watusi","waxworks","waza-ari","Wazir","waṣla","WBW","weakfish","Weapemeoc","weatherfish","weaverfish","Webelos","wedgefish","weeverfish","wels","Welsh","Wemale","wemistikoshiw","wendigo","weta","wetu","whalefish","whanau","whānau","whereabouts","whitebass","whitefish","whiting","Wichí","Wichita","wildebeest","wildfowl","Willapa","windigo","wingfish","Wintun","witfish","WMD","WOC","wokefish","wolf-fish","wolffish","wolfkin","Wolof","wolven","wombyn","womxn","womyn","womyn-born-womyn","won","woodcock","woodgrouse","woodworks","woolworks","wormfish","worryguts","wors","WPM","wpm","wreckfish","WRULD","wu","Wuhanese","Wyandot","Wyandotte","X-craft","xanith","Xavante","Xavánte","Xhosa","xianbing","xiaolongbao","Xibe","Xicaque","xiehouyu","xiucai","Xokleng","Xoloitzcuintli","xorn","XP","xu","Xyl.","y.o.","Yabim","yadu","Yaghan","Yaghnobi","Yagnobi","yagura","yaguranage","Yahgan","yak","yakata","Yakima","yakin","yakitori","Yakoot","Yakut","yakuza","yamabushi","Yamacraw","yamamomo","yamanba","Yamasee","Yamassee","Yamato","Yana","yanakuna","yangban","Yankton","Yanktonai","yaoi","Yapese","yard-fowl","yardfowl","yari","yashiro","yatai","yellowfin","yellowfish","yellowshanks","yellowshins","yen","yeti","yobidashi","yobimodoshi","yokai","yokozuna","Yolngu","Yomud","Yomut","yonkoma","yonsei","yoriki","yorikiri","yoritaoshi","yottahertz","youkai","young","youthman","youtiao","ypogegrammeni","Yprois","yu","yuan","Yucatec","Yucateco","Yuchi","yueqin","yugarie","yukata","yuki-onna","yumi","yumitori-shiki","yumoji","yunluo","Yup'ik","Yupik","Yurok","Zabaleen","Zabbaleen","zaibatsu","zaikai","zaïre","zaisu","zamioculcas","zander","zandoli","Zapotec","Zardushti","Zarma","Zaza","zebra","zebrafish","zeitgeber","Zerma","Zhangzhounese","zhiqing","Zhmud","zhong-hu","zhonghu","zhu","Zhuang","zhuangyuan","zhuihu","zhuiqin","ziege","zimbi","Zirak","zloty","zongdu","zongzi","zoodetritus","zooplankton","Zoque","zori","zubuneri","zucchini","Zulu","zun","Zuricher","Zwartbles","Zweihänder","øre","ʻukulele"]
    
    irregularverbs = ["arise","awake","be","bear","beat","become","begin","bend","bet","bind","bite","bleed","blow","break","breed","bring","broadcast","build","burn","burst","buy","can","catch","choose","cling","come","cost","creep","cut","deal","dig","do","draw","dream","drink","drive","eat","fall","feed","feel","fight","find","fly","forbid","forget","forgive","freeze","get","give","go","grind","grow","hang","have","hear","hide","hit","hold","hurt","keep","kneel","know","lay","lead","lean","learn","leave","lend","lie","light","lose","make","may","mean","meet","mow","must","overtake","pay","put","read","ride","ring","rise","run","saw","say","see","sell","send","set","sew","shake","shall","shed","shine","shoot","show","shrink","shut","sing","sink","sit","sleep","slide","smell","sow","speak","spell","spend","spill","spit","spread","stand","steal","stick","sting","stink","strike","swear","sweep","swell","swim","swing","take","teach","tear","tell","think","throw","understand","wake","wear","weep","will","win","wind","write"]

    conjugaisonReg={
        "ing":"Present Participle",
        "ed":"Past Participle"
    }
    
    conjugaisonIrrReg = {
        "ing":"Present Participle",
        "underfeed":"Infinitif",
"misgave":"Past of misgive",
"been":"Past Participle of be",
"saken":"Past Participle of sake",
"overdress":"Infinitif",
"outran":"Past of outrun",
"light":"Infinitif",
"partake":"Infinitif",
"forswore":"Past of forswear",
"burst":"Past of burst",
"pent":"Past of pen",
"sodden":"Past Participle of seethe",
"fall":"Infinitif",
"reshoot":"Infinitif",
"fallen":"Past Participle of fall",
"will":"Infinitif",
"outgrown":"Past Participle of outgrow",
"forlain":"Past Participle of forelie",
"beat":"Past of beat",
"overshot":"Past of overshoot",
"withhold":"Infinitif",
"overdrove":"Past of overdrive",
"reave":"Infinitif",
"stood":"Past of stand",
"underpaid":"Past of underpay",
"miskent":"Past of misken",
"sowed":"Past of sow",
"forborne":"Past Participle of forbear",
"overbid":"Infinitif",
"learn":"Infinitif",
"stang":"Past of sting",
"mow":"Infinitif",
"underlet":"Past of underlet",
"arose":"Past of arise",
"broughten":"Past Participle of bring",
"spread":"Past of spread",
"grew":"Past of grow",
"sow":"Infinitif",
"overbuild":"Infinitif",
"spin":"Infinitif",
"underlie":"Infinitif",
"prepay":"Infinitif",
"bequoth":"Past of bequeath",
"overset":"Infinitif",
"outthrust":"Past of outthrust",
"bore":"Past of bear",
"misspell":"Infinitif",
"sweep":"Infinitif",
"ride":"Infinitif",
"slang":"Past of sling",
"held":"Past of hold",
"hanged":"Past of hang",
"strived":"Past of strive",
"thrust":"Past of thrust",
"upset":"Infinitif",
"choose":"Infinitif",
"outthought":"Past of outthink",
"overblown":"Past Participle of overblow",
"break":"Infinitif",
"bequeath":"Infinitif",
"stridden":"Past Participle of stride",
"spake":"Past of speak",
"unbend":"Infinitif",
"hang":"Infinitif",
"shown":"Past Participle of show",
"dive":"Infinitif",
"overswing":"Infinitif",
"miskept":"Past of miskeep",
"set":"Infinitif",
"hurt":"Past of hurt",
"overrode":"Past of override",
"sprung":"Past of spring",
"wedded":"Past of wed",
"forsay":"Infinitif",
"overspend":"Infinitif",
"outsung":"Past Participle of outsing",
"send":"Infinitif",
"strode":"Past of stride",
"undo":"Infinitif",
"string":"Infinitif",
"deal":"Infinitif",
"drave":"Past of drive",
"podcast":"Past of podcast",
"overdrank":"Past of overdrink",
"spilt":"Past of spill",
"besought":"Past of beseech",
"stuck":"Past of stick",
"set":"Past of set",
"nam":"Past of nim",
"melted":"Past of melt",
"leant":"Past of lean (UK)",
"interweave":"Infinitif",
"swelt":"Infinitif",
"withdraw":"Infinitif",
"shoot":"Infinitif",
"stunk":"Past of stink",
"partook":"Past of partake",
"overspilled":"Past of overspill",
"swelted":"Past of swelt",
"oversleep":"Infinitif",
"rethought":"Past of rethink",
"underlet":"Infinitif",
"done":"Past Participle of do",
"catch":"Infinitif",
"bear":"Infinitif",
"overbid":"Past of overbid",
"knit":"Infinitif",
"underdig":"Infinitif",
"forewent":"Past of forego",
"repaid":"Past of repay",
"hide":"Infinitif",
"smelled":"Past of smell",
"wrang":"Past of wring",
"input":"Past of input",
"grow":"Infinitif",
"overpay":"Infinitif",
"reread":"Infinitif",
"beshine":"Infinitif",
"forget":"Infinitif",
"dress":"Infinitif",
"strid":"Past Participle of stride",
"shrink":"Infinitif",
"overbore":"Past of overbear",
"bursten":"Past Participle of burst",
"ken":"Infinitif",
"hew":"Past of hew",
"overslept":"Past of oversleep",
"spill":"Infinitif",
"drove":"Past of drive",
"underlay":"Past of underlie",
"laden":"Past Participle of lade",
"foresee":"Infinitif",
"drunk":"Past of drink",
"undertook":"Past of undertake",
"overborne":"Past Participle of overbear",
"drest":"Past of dress",
"ridded":"Past of rid",
"overstrode":"Past of overstride",
"build":"Infinitif",
"outshone":"Past of outshine",
"sublet":"Past of sublet",
"beget":"Infinitif",
"overbear":"Infinitif",
"lade":"Infinitif",
"forbade":"Past of forbid",
"leap":"Infinitif",
"forsake":"Infinitif",
"shot":"Past of shoot",
"begat":"Past of beget",
"overshoot":"Infinitif",
"write":"Infinitif",
"shake":"Infinitif",
"hear":"Infinitif",
"outbid":"Infinitif",
"broke":"Past of break",
"spent":"Past of spend",
"outgrow":"Infinitif",
"riven":"Past Participle of rive",
"may":"Infinitif",
"weaved":"Past of weave",
"misdo":"Infinitif",
"remake":"Infinitif",
"shut":"Past of shut",
"stand":"Infinitif",
"underwrote":"Past of underwrite",
"forsaid":"Past of forsay",
"overslipped":"Past of overslip",
"kneel":"Infinitif",
"outgrew":"Past of outgrow",
"shriven":"Past Participle of shrive",
"misspoke":"Past of misspeak",
"underdraw":"Infinitif",
"flown":"Past Participle of fly",
"wax":"Infinitif",
"bespeak":"Infinitif",
"strung":"Past of string",
"undergrown":"Past Participle of undergrow",
"span":"Past of spin",
"dwell":"Infinitif",
"stolen":"Past Participle of steal",
"undergo":"Infinitif",
"sod":"Past of seethe",
"overdrawn":"Past Participle of overdraw",
"sew":"Infinitif",
"swim":"Infinitif",
"learned":"Past of learn",
"writhe":"Infinitif",
"unbound":"Past of unbind",
"overslide":"Infinitif",
"forlaft":"Past Participle of forleave",
"known":"Past Participle of know",
"foreknew":"Past of foreknow",
"reshot":"Past of reshoot",
"broken":"Past Participle of break",
"burst":"Infinitif",
"weep":"Infinitif",
"not":"Past Participle of lie",
"frore":"Past of freeze",
"bespread":"Infinitif",
"overcast":"Infinitif",
"unbind":"Infinitif",
"have":"Infinitif",
"mown":"Past Participle of mow",
"bended":"Past of bend",
"misget":"Infinitif",
"undrest":"Past of undress",
"hew":"Infinitif",
"snuck":"Past of sneak",
"sneak":"Infinitif",
"prove":"Infinitif",
"withset":"Past of withset",
"clothe":"Infinitif",
"bespoke":"Past of bespeak",
"told":"Past of tell",
"bound":"Past of bind",
"found":"Past of find",
"outthrust":"Infinitif",
"overshine":"Infinitif",
"mischosen":"Past Participle of mischoose",
"nim":"Infinitif",
"bode":"Past of bide",
"browbeat":"Infinitif",
"drew":"Past of draw",
"strang":"Past of string",
"knitted":"Past of knit",
"teach":"Infinitif",
"misdid":"Past of misdo",
"clad":"Past of clothe",
"stink":"Infinitif",
"shapen":"Past Participle of shape",
"shorn":"Past Participle of shear",
"misshape":"Infinitif",
"grinded":"Past of grind",
"overshook":"Past of overshake",
"misshapen":"Past Participle of misshape",
"bounden":"Past Participle of bind",
"might":"Past of may",
"forlet":"Infinitif",
"knit":"Past of knit",
"overslip":"Infinitif",
"heaved":"Past of heave",
"underbought":"Past of underbuy",
"forlay":"Past of forelie",
"wrote":"Past of write",
"forgive":"Infinitif",
"saw":"Infinitif",
"cost":"Past of cost",
"mistook":"Past of mistake",
"forbad":"Past of forbid",
"spit":"Past of spit",
"outsing":"Infinitif",
"go":"Past Participle of Suppletive.",
"misspoken":"Past Participle of misspeak",
"mislay":"Infinitif",
"forecast":"Infinitif",
"shotten":"Past Participle of shoot",
"underbound":"Past of underbind",
"written":"Past Participle of write",
"overstridden":"Past Participle of overstride",
"chode":"Past of chide",
"swing":"Infinitif",
"reread":"Past of reread",
"spoken":"Past Participle of speak",
"webcast":"Past of webcast",
"inbreed":"Infinitif",
"wrung":"Past of wring",
"hove":"Past of heave",
"mishear":"Infinitif",
"overfeed":"Infinitif",
"offset":"Past of offset",
"lent":"Past of lend",
"fled":"Past of flee",
"nimmed":"Past of nim",
"dwelt":"Past of dwell",
"strewn":"Past Participle of strew",
"misborne":"Past Participle of misbear",
"knew":"Past of know",
"oversold":"Past of oversell",
"clothed":"Past of clothe",
"thrusted":"Past Participle of thrust",
"overshone":"Past of overshine",
"crow":"Infinitif",
"inset":"Past of inset",
"browbeat":"Past of browbeat",
"resend":"Infinitif",
"dragged":"Past of drag",
"beset":"Past of beset",
"overbought":"Past of overbuy",
"lay":"Infinitif",
"retrod":"Past of retread",
"flee":"Infinitif",
"sweat":"Infinitif",
"sank":"Past of sink",
"speak":"Infinitif",
"underdress":"Infinitif",
"overspread":"Past of overspread",
"underlay":"Infinitif",
"overlain":"Past Participle of overlie",
"beseeched":"Past of beseech",
"forgave":"Past of forgive",
"founden":"Past Participle of find",
"forgo":"Infinitif",
"befallen":"Past Participle of befall",
"born":"Past Participle of bear",
"rent":"Past of rend",
"overlay":"Past of overlie",
"beat":"Infinitif",
"stride":"Infinitif",
"miskeep":"Infinitif",
"undergird":"Infinitif",
"rung":"Past Participle of ring",
"outtold":"Past of outtell",
"woven":"Past Participle of weave",
"proofread":"Past of proofread",
"can":"Infinitif",
"hid":"Past of hide",
"beseech":"Infinitif",
"underdone":"Past Participle of underdo",
"fell":"Past of fall",
"underwritten":"Past Participle of underwrite",
"misspelt":"Past of misspell",
"bequeathed":"Past of bequeath",
"heave":"Infinitif",
"run":"Infinitif",
"outputted":"Past of output",
"bend":"Infinitif",
"grown":"Past Participle of grow",
"molten":"Past Participle of melt",
"betted":"Past of bet",
"sworn":"Past Participle of swear",
"strown":"Past Participle of strow",
"drag":"Infinitif",
"overdressed":"Past of overdress",
"sent":"Past of send",
"buy":"Infinitif",
"undergotten":"Past Participle of underget",
"chidden":"Past Participle of chide",
"redo":"Infinitif",
"abide":"Infinitif",
"sought":"Past of seek",
"misread":"Past of misread",
"mislaid":"Past of mislay",
"missent":"Past of missend",
"shed":"Past of shed",
"lie":"Infinitif",
"writhed":"Past of writhe",
"shoe":"Infinitif",
"underdid":"Past of underdo",
"clung":"Past of cling",
"throve":"Past of thrive",
"underhew":"Infinitif",
"mean":"Infinitif",
"worth":"Infinitif",
"girded":"Past of gird",
"ground":"Past of grind",
"rethink":"Infinitif",
"behold":"Infinitif",
"underbore":"Past of underbear",
"overshaken":"Past Participle of overshake",
"blown":"Past Participle of blow",
"overfly":"Infinitif",
"bespread":"Past of bespread",
"gone":"Past Participle of go",
"overshake":"Infinitif",
"sown":"Past Participle of sow",
"proofread":"Infinitif",
"outbid":"Past of outbid",
"overhung":"Past of overhang",
"trodden":"Past Participle of tread",
"beaten":"Past Participle of beat",
"sawed":"Past of saw",
"miswrote":"Past of miswrite",
"had":"Past of have",
"blest":"Past of bless",
"bid":"Past of bid",
"risen":"Past Participle of rise",
"rebuilt":"Past of rebuild",
"lipread":"Past of lipread",
"prepaid":"Past of prepay",
"given":"Past Participle of give",
"fit":"Past of fit",
"rend":"Infinitif",
"interwove":"Past of interweave",
"chose":"Past of choose",
"bid":"Infinitif",
"became":"Past of become",
"wreaked":"Past of wreak",
"misdealt":"Past of misdeal",
"would":"Past of will",
"unclad":"Past of unclothe",
"overspread":"Infinitif",
"smite":"Infinitif",
"bare":"Past of bear",
"mishit":"Infinitif",
"ring":"Infinitif",
"busted":"Past of bust",
"overhear":"Infinitif",
"oversaw":"Past of oversee",
"read":"Past of read",
"overfed":"Past of overfeed",
"stole":"Past of steal",
"strow":"Past of strow",
"wrought":"Past of work",
"overlie":"Infinitif",
"retake":"Infinitif",
"underdrawn":"Past Participle of underdraw",
"naysaid":"Past of naysay",
"withdrawn":"Past Participle of withdraw",
"retold":"Past of retell",
"shrive":"Infinitif",
"think":"Infinitif",
"driven":"Past Participle of drive",
"overeaten":"Past Participle of overeat",
"repay":"Infinitif",
"forlay":"Infinitif",
"shape":"Infinitif",
"unclothed":"Past of unclothe",
"misgot":"Past of misget",
"misbecame":"Past of misbecome",
"blew":"Past of blow",
"bereaved":"Past of bereave",
"outdid":"Past of outdo",
"meant":"Past of mean",
"abidden":"Past Participle of abide",
"gnew":"Past of gnaw",
"bit":"Past of bite",
"sweat":"Past of sweat",
"crept":"Past of creep",
"forbid":"Past of forbid",
"leapt":"Past of leap",
"led":"Past of lead",
"stricken":"Past Participle of strike",
"swum":"Past Participle of swim",
"oversewed":"Past of oversew",
"input":"Infinitif",
"overbred":"Past of overbreed",
"gild":"Infinitif",
"dwelled":"Past of dwell",
"make":"Infinitif",
"withstood":"Past of withstand",
"felt":"Past of feel",
"resell":"Infinitif",
"stung":"Past of sting",
"foreran":"Past of forerun",
"thrusted":"Past of thrust",
"mistake":"Infinitif",
"wring":"Infinitif",
"know":"Infinitif",
"forspent":"Past of forspend",
"won":"Past of win",
"overspill":"Infinitif",
"seethe":"Infinitif",
"resent":"Past of resend",
"could":"Past of can",
"bless":"Infinitif",
"redraw":"Infinitif",
"woke":"Past of wake",
"stove":"Past of stave",
"beheld":"Past of behold",
"forgone":"Past Participle of forgo",
"slidden":"Past Participle of slide",
"benam":"Past of benim",
"rewrite":"Infinitif",
"strike":"Infinitif",
"bent":"Past of bend",
"shaken":"Past Participle of shake",
"spat":"Past of spit",
"came":"Past of come",
"begotten":"Past Participle of beget",
"swell":"Infinitif",
"underhung":"Past of underhang",
"forelay":"Infinitif",
"sit":"Infinitif",
"undercast":"Past of undercast",
"work":"Infinitif",
"quit":"Infinitif",
"stick":"Infinitif",
"let":"Infinitif",
"overlaid":"Past of overlay",
"benimmed":"Past of benim",
"preset":"Past of preset",
"keep":"Infinitif",
"striven":"Past Participle of strive",
"wept":"Past of weep",
"kenned":"Past of ken",
"overworked":"Past of overwork",
"standen":"Past Participle of stand",
"laded":"Past of lade",
"hewn":"Past Participle of hew",
"wroke":"Past of wreak",
"sling":"Infinitif",
"foreknow":"Infinitif",
"hamstring":"Infinitif",
"dig":"Infinitif",
"underwent":"Past of undergo",
"brast":"Past of burst",
"spelt":"Past of spell",
"split":"Past of split",
"missend":"Infinitif",
"slain":"Past Participle of slay",
"spoke":"Past of speak",
"blow":"Infinitif",
"wetted":"Past of wet",
"strew":"Past of strew",
"misset":"Past of misset",
"rewound":"Past of rewind",
"froze":"Past of freeze",
"couth":"Past Participle of can",
"creep":"Infinitif",
"foresaw":"Past of foresee",
"eaten":"Past Participle of eat",
"overcast":"Past of overcast",
"weave":"Infinitif",
"withsaid":"Past of withsay",
"taken":"Past Participle of take",
"misheard":"Past of mishear",
"redid":"Past of redo",
"strewed":"Past of strew",
"grounden":"Past Participle of grind",
"gilt":"Past of gild",
"rang":"Past of ring",
"pen":"Infinitif",
"strew":"Infinitif",
"ran":"Past of run",
"freeze":"Infinitif",
"lighted":"Past of light",
"mislearn":"Infinitif",
"swolten":"Past Participle of swelt",
"waylay":"Infinitif",
"cleave":"Infinitif",
"bided":"Past of bide",
"sightseen":"Past Participle of sightsee",
"misbegot":"Past of misbeget",
"forlend":"Infinitif",
"undergirt":"Past of undergird",
"did":"Past of do",
"queath":"Infinitif",
"misken":"Infinitif",
"slit":"Past of slit",
"interwoven":"Past Participle of interweave",
"outsworn":"Past Participle of outswear",
"broadcast":"Infinitif",
"undertaken":"Past Participle of undertake",
"lit":"Past of light",
"rerun":"Infinitif",
"missay":"Infinitif",
"misspeak":"Infinitif",
"bust":"Infinitif",
"intercut":"Past of intercut",
"numb":"Past Participle of nim",
"nome":"Past Participle of nim",
"webcast":"Infinitif",
"outswear":"Infinitif",
"overdrive":"Infinitif",
"miswritten":"Past Participle of miswrite",
"dressed":"Past of dress",
"oversell":"Infinitif",
"flung":"Past of fling",
"win":"Infinitif",
"shoed":"Past of shoe",
"resold":"Past of resell",
"learnt":"Past of learn",
"feed":"Infinitif",
"sawn":"Past Participle of saw",
"bide":"Infinitif",
"inbred":"Past of inbreed",
"shined":"Past of shine",
"misshaped":"Past of misshape",
"worn":"Past Participle of wear",
"misgive":"Infinitif",
"come":"Infinitif",
"rived":"Past of rive",
"leaned":"Past of lean (US)",
"quethe":"Past Participle of queath",
"chidded":"Past of chide",
"overtook":"Past of overtake",
"made":"Past of make",
"shook":"Past of shake",
"inlaid":"Past of inlay",
"molt":"Past of melt",
"forleft":"Past of forleave",
"fed":"Past of feed",
"breastfed":"Past of breastfeed",
"partaken":"Past Participle of partake",
"underbind":"Infinitif",
"outshine":"Infinitif",
"proven":"Past Participle of prove",
"strowed":"Past of strow",
"crew":"Past of crow",
"forecast":"Past of forecast",
"overflew":"Past of overfly",
"outswore":"Past of outswear",
"miscast":"Past of miscast",
"misgotten":"Past Participle of misget",
"took":"Past of take",
"podcast":"Infinitif",
"sweated":"Past of sweat",
"overhang":"Infinitif",
"sung":"Past Participle of sing",
"miscast":"Infinitif",
"outsell":"Infinitif",
"underhewn":"Past Participle of underhew",
"writhen":"Past Participle of writhe",
"hit":"Infinitif",
"misunderstood":"Past of misunderstand",
"slid":"Past of slide",
"hamstrung":"Past of hamstring",
"sewn":"Past Participle of sew",
"hurt":"Infinitif",
"recast":"Infinitif",
"caught":"Past of catch",
"bitten":"Past Participle of bite",
"forspend":"Infinitif",
"underran":"Past of underrun",
"forspoken":"Past Participle of forspeak",
"dreamed":"Past of dream",
"beshone":"Past of beshine",
"forlet":"Past of forlet",
"alighted":"Past of alight",
"dream":"Infinitif",
"bereft":"Past of bereave",
"go":"Infinitif",
"underbear":"Infinitif",
"overdid":"Past of overdo",
"overbuy":"Infinitif",
"forlent":"Past of forlend",
"shew":"Past of show",
"miskenned":"Past of misken",
"dealt":"Past of deal",
"misspend":"Infinitif",
"went":"Past of wend",
"overwork":"Infinitif",
"missaid":"Past of missay",
"inset":"Infinitif",
"steal":"Infinitif",
"kept":"Past of keep",
"sink":"Infinitif",
"outspent":"Past of outspend",
"abode":"Past of abide",
"burnt":"Past of burn",
"overbend":"Infinitif",
"benomen":"Past Participle of benim",
"thrust":"Infinitif",
"gilded":"Past of gild",
"retread":"Infinitif",
"forgot":"Past of forget",
"leaped":"Past of leap",
"heard":"Past of hear",
"tear":"Infinitif",
"undress":"Infinitif",
"outspend":"Infinitif",
"mislead":"Infinitif",
"overslipt":"Past of overslip",
"sped":"Past of speed",
"give":"Infinitif",
"clang":"Past of cling",
"misunderstand":"Infinitif",
"undergone":"Past Participle of undergo",
"wed":"Infinitif",
"clept":"Past of clepe",
"shrunken":"Past Participle of shrink",
"sprang":"Past of spring",
"wreaken":"Past Participle of wreak",
"upheld":"Past of uphold",
"underdo":"Infinitif",
"underhang":"Infinitif",
"overwrite":"Infinitif",
"tread":"Infinitif",
"gotten":"Past Participle of get",
"paid":"Past of pay",
"overdriven":"Past Participle of overdrive",
"hit":"Past of hit",
"cut":"Past of cut",
"shat":"Past of shit",
"wed":"Past of wed",
"underbid":"Infinitif",
"offset":"Infinitif",
"leet":"Past Participle of let",
"overslid":"Past of overslide",
"bursted":"Past of burst",
"shit":"Past of shite",
"thrown":"Past Participle of throw",
"foreseen":"Past Participle of foresee",
"shed":"Infinitif",
"wake":"Infinitif",
"holden":"Past Participle of hold",
"undercut":"Infinitif",
"mislearned":"Past of mislearn",
"befell":"Past of befall",
"clepe":"Infinitif",
"undressed":"Past of undress",
"shone":"Past of shine",
"met":"Past of meet",
"shaved":"Past of shave",
"understood":"Past of understand",
"slunk":"Past of slink",
"forgotten":"Past Participle of forget",
"smitten":"Past Participle of smite",
"foretold":"Past of foretell",
"understand":"Infinitif",
"get":"Infinitif",
"overcame":"Past of overcome",
"hewed":"Past of hew",
"was":"Past of be",
"spell":"Infinitif",
"wend":"Infinitif",
"misknow":"Infinitif",
"read":"Infinitif",
"shodden":"Past Participle of shoe",
"chosen":"Past Participle of choose",
"grind":"Infinitif",
"chid":"Past of chide",
"gainsay":"Infinitif",
"overthrow":"Infinitif",
"overwrought":"Past Participle of overwork",
"overlay":"Infinitif",
"shrove":"Past of shrive",
"forelie":"Infinitif",
"forbid":"Infinitif",
"forsaken":"Past Participle of forsake",
"overbreed":"Infinitif",
"overgrown":"Past Participle of overgrow",
"spelled":"Past of spell",
"swang":"Past of swing",
"overrun":"Infinitif",
"hold":"Infinitif",
"went":"Past of go",
"overate":"Past of overeat",
"overdrew":"Past of overdraw",
"seethed":"Past of seethe",
"outtell":"Infinitif",
"dreamt":"Past of dream",
"slew":"Past of slay",
"relaid":"Past of relay",
"overtaken":"Past Participle of overtake",
"forspeak":"Infinitif",
"built":"Past of build",
"girt":"Past of gird",
"gave":"Past of give",
"besee":"Infinitif",
"withdrew":"Past of withdraw",
"overdo":"Infinitif",
"underget":"Infinitif",
"woken":"Past Participle of wake",
"do":"Infinitif",
"bite":"Infinitif",
"crown":"Past Participle of crow",
"struck":"Past of strike",
"swollen":"Past Participle of swell",
"spoilt":"Past of spoil",
"foughten":"Past Participle of fight",
"benome":"Past Participle of benim",
"spoiled":"Past of spoil",
"outshined":"Past of outshine",
"outsang":"Past of outsing",
"hidden":"Past Participle of hide",
"sightsaw":"Past of sightsee",
"outsold":"Past of outsell",
"alit":"Past of alight",
"dug":"Past of dig",
"outthrown":"Past Participle of outthrow",
"laid":"Past of lay",
"awoken":"Past Participle of awake",
"broadcast":"Past of broadcast",
"crowed":"Past of crow",
"shore":"Past of shear",
"undercut":"Past of undercut",
"swelled":"Past of swell",
"overblow":"Infinitif",
"breastfeed":"Infinitif",
"retook":"Past of retake",
"burned":"Past of burn",
"lose":"Infinitif",
"spoil":"Infinitif",
"cast":"Infinitif",
"reset":"Past of reset",
"underdressed":"Past of underdress",
"beseen":"Past Participle of besee",
"smit":"Past of smite",
"reft":"Past of reave",
"naysay":"Infinitif",
"fly":"Infinitif",
"wrought":"Past of wreak",
"stave":"Infinitif",
"gainsaid":"Past of gainsay",
"burn":"Infinitif",
"stay":"Infinitif",
"trod":"Past of tread",
"overpaid":"Past of overpay",
"regrown":"Past Participle of regrow",
"simulcast":"Past of simulcast",
"overdrunk":"Past Participle of overdrink",
"begin":"Infinitif",
"said":"Past of say",
"forbore":"Past of forbear",
"undergirded":"Past of undergird",
"knelt":"Past of kneel",
"simulcast":"Infinitif",
"hung":"Past of hang",
"overdrest":"Past of overdress",
"overshined":"Past of overshine",
"thrive":"Infinitif",
"draw":"Infinitif",
"shave":"Infinitif",
"undershoot":"Infinitif",
"awoke":"Past of awake",
"outdo":"Infinitif",
"say":"Infinitif",
"overthrew":"Past of overthrow",
"underdrew":"Past of underdraw",
"underbuy":"Infinitif",
"overswung":"Past of overswing",
"fought":"Past of fight",
"overstride":"Infinitif",
"pay":"Infinitif",
"swoll":"Past of swell",
"underdug":"Past of underdig",
"thriven":"Past Participle of thrive",
"strided":"Past of stride",
"shine":"Infinitif",
"rewritten":"Past Participle of rewrite",
"oversew":"Infinitif",
"tell":"Infinitif",
"drawn":"Past Participle of draw",
"redrawn":"Past Participle of redraw",
"forsook":"Past of forsake",
"abided":"Past of abide",
"bled":"Past of bleed",
"bequeathen":"Past Participle of bequeath",
"wind":"Infinitif",
"throw":"Infinitif",
"dared":"Past of dare",
"overhanged":"Past of overhang",
"interbreed":"Infinitif",
"put":"Past of put",
"forgiven":"Past Participle of forgive",
"strove":"Past of strive",
"tore":"Past of tear",
"forsworn":"Past Participle of forswear",
"foreknown":"Past Participle of foreknow",
"frozen":"Past Participle of freeze",
"regrew":"Past of regrow",
"sewed":"Past of sew",
"writ":"Past of write",
"dived":"Past of dive",
"sleep":"Infinitif",
"retrodden":"Past Participle of retread",
"overtake":"Infinitif",
"mischose":"Past of mischoose",
"borne":"Past Participle of bear",
"foretell":"Infinitif",
"misfed":"Past of misfeed",
"chide":"Infinitif",
"overridden":"Past Participle of override",
"overwrote":"Past of overwrite",
"lost":"Past of lose",
"lipread":"Infinitif",
"unclothe":"Infinitif",
"outrun":"Infinitif",
"benim":"Infinitif",
"bade":"Past of bid",
"shit":"Past of shit",
"durst":"Past of dare",
"ate":"Past of eat",
"shaped":"Past of shape",
"strow":"Infinitif",
"spring":"Infinitif",
"meet":"Infinitif",
"forleave":"Infinitif",
"fling":"Infinitif",
"begun":"Past Participle of begin",
"bind":"Infinitif",
"shut":"Infinitif",
"misset":"Infinitif",
"withholden":"Past Participle of withhold",
"overthrown":"Past Participle of overthrow",
"kneeled":"Past of kneel",
"gnawed":"Past of gnaw",
"overflown":"Past Participle of overfly",
"preset":"Infinitif",
"befall":"Infinitif",
"sightsee":"Infinitif",
"rise":"Infinitif",
"heft":"Past Participle of heave",
"nomen":"Past Participle of nim",
"swung":"Past of swing",
"lopen":"Past Participle of leap",
"were":"Past of be",
"find":"Infinitif",
"misknew":"Past of misknow",
"underfed":"Past of underfeed",
"overblew":"Past of overblow",
"overheard":"Past of overhear",
"browbeaten":"Past Participle of browbeat",
"mislearnt":"Past of mislearn",
"sunken":"Past Participle of sink",
"lope":"Past of leap",
"forlaid":"Past of forlay",
"rid":"Past of rid",
"beset":"Infinitif",
"waxed":"Past of wax",
"rid":"Infinitif",
"dove":"Past of dive",
"smell":"Infinitif",
"sew":"Past of sow",
"undershot":"Past of undershoot",
"underborne":"Past Participle of underbear",
"wove":"Past of weave",
"swam":"Past of swim",
"willed":"Past of will",
"undertake":"Infinitif",
"misdone":"Past Participle of misdo",
"arise":"Infinitif",
"spit":"Infinitif",
"cropen":"Past Participle of creep",
"outdone":"Past Participle of outdo",
"sing":"Infinitif",
"see":"Infinitif",
"overeat":"Infinitif",
"undone":"Past Participle of undo",
"staved":"Past of stave",
"lean":"Infinitif",
"dare":"Infinitif",
"overdone":"Past Participle of overdo",
"uphold":"Infinitif",
"worthen":"Past Participle of worth",
"forerun":"Infinitif",
"sneaked":"Past of sneak",
"eat":"Infinitif",
"slipt":"Past of slip",
"forbear":"Infinitif",
"shall":"Infinitif",
"forego":"Infinitif",
"overspent":"Past of overspend",
"wore":"Past of wear",
"blessed":"Past of bless",
"slung":"Past of sling",
"cast":"Past of cast",
"overgrow":"Infinitif",
"sunk":"Past of sink",
"grove":"Past of grave",
"mishit":"Past of mishit",
"sold":"Past of sell",
"overset":"Past of overset",
"slay":"Infinitif",
"rebuild":"Infinitif",
"reran":"Past of rerun",
"slink":"Infinitif",
"bet":"Past of bet",
"shope":"Past of shape",
"shit":"Infinitif",
"underlain":"Past Participle of underlie",
"slip":"Infinitif",
"shat":"Past of shite",
"thrived":"Past of thrive",
"bespoken":"Past Participle of bespeak",
"swear":"Infinitif",
"undergot":"Past of underget",
"gird":"Infinitif",
"drank":"Past of drink",
"regrow":"Infinitif",
"overdraw":"Infinitif",
"or":"Past of queath",
"forswear":"Infinitif",
"penned":"Past of pen",
"overslidden":"Past Participle of overslide",
"outthrow":"Infinitif",
"misbegotten":"Past Participle of misbeget",
"oversewn":"Past Participle of oversew",
"misspent":"Past of misspend",
"retaken":"Past Participle of retake",
"hoven":"Past Participle of heave",
"babysat":"Past of babysit",
"crosscut":"Past of crosscut",
"drunken":"Past Participle of drink",
"undergrew":"Past of undergrow",
"yclept":"Past Participle of clepe",
"taught":"Past of teach",
"undercast":"Infinitif",
"mischoose":"Infinitif",
"sublet":"Infinitif",
"slept":"Past of sleep",
"foregone":"Past Participle of forego",
"breed":"Infinitif",
"misbear":"Infinitif",
"swore":"Past of swear",
"miswrite":"Infinitif",
"underbid":"Past of underbid",
"crosscut":"Infinitif",
"forspoke":"Past of forspeak",
"misbeget":"Infinitif",
"wrothe":"Past of writhe",
"wreak":"Infinitif",
"worked":"Past of work",
"shite":"Infinitif",
"withstand":"Infinitif",
"rewind":"Infinitif",
"wroken":"Past Participle of wreak",
"spilled":"Past of spill",
"redrew":"Past of redraw",
"withheld":"Past of withhold",
"misread":"Infinitif",
"babysit":"Infinitif",
"bred":"Past of breed",
"overbuilt":"Past of overbuild",
"awake":"Infinitif",
"kent":"Past of ken",
"gnaw":"Infinitif",
"rewrote":"Past of rewrite",
"seen":"Past Participle of see",
"stank":"Past of stink",
"overgrew":"Past of overgrow",
"shaven":"Past Participle of shave",
"rode":"Past of ride",
"sat":"Past of sit",
"override":"Infinitif",
"inlay":"Infinitif",
"sang":"Past of sing",
"overran":"Past of overrun",
"shear":"Infinitif",
"fit":"Infinitif",
"arisen":"Past Participle of arise",
"pled":"Past of plead",
"redone":"Past Participle of redo",
"bereave":"Infinitif",
"began":"Past of begin",
"staid":"Past of stay",
"slipped":"Past of slip",
"cost":"Infinitif",
"froren":"Past Participle of freeze",
"shrunk":"Past of shrink",
"boughten":"Past Participle of buy",
"fitted":"Past of fit",
"rose":"Past of rise",
"grave":"Infinitif",
"lend":"Infinitif",
"overseen":"Past Participle of oversee",
"smelt":"Past of smell",
"output":"Past of output",
"forwent":"Past of forgo",
"slit":"Infinitif",
"misknown":"Past Participle of misknow",
"gnawn":"Past Participle of gnaw",
"seek":"Infinitif",
"bust":"Past of bust",
"melt":"Infinitif",
"torn":"Past Participle of tear",
"oversee":"Infinitif",
"unwind":"Infinitif",
"spread":"Infinitif",
"misfeed":"Infinitif",
"upset":"Past of upset",
"misspelled":"Past of misspell",
"flew":"Past of fly",
"graven":"Past Participle of grave",
"outthink":"Infinitif",
"wet":"Infinitif",
"withsay":"Infinitif",
"wound":"Past of wind",
"proved":"Past of prove",
"overspilt":"Past of overspill",
"bring":"Infinitif",
"drink":"Infinitif",
"misgiven":"Past Participle of misgive",
"misled":"Past of mislead",
"spend":"Infinitif",
"reset":"Infinitif",
"recast":"Past of recast",
"underlaid":"Past of underlay",
"underrun":"Infinitif",
"should":"Past of shall",
"underdrest":"Past of underdress",
"cling":"Infinitif",
"spun":"Past of spin",
"overcome":"Infinitif",
"benumb":"Past Participle of benim",
"swept":"Past of sweep",
"underwrite":"Infinitif",
"be":"Infinitif",
"overdrink":"Infinitif",
"saw":"Past of see",
"undid":"Past of undo",
"brought":"Past of bring",
"take":"Infinitif",
"put":"Infinitif",
"misbecome":"Infinitif",
"underpay":"Infinitif",
"shod":"Past of shoe",
"forelaid":"Past of forelay",
"graved":"Past of grave",
"underhewed":"Past of underhew",
"feel":"Infinitif",
"become":"Infinitif",
"creeped":"Past of creep",
"withset":"Infinitif",
"upholden":"Past Participle of uphold",
"relay":"Infinitif",
"plead":"Infinitif",
"alight":"Infinitif",
"shedded":"Past of shed",
"strive":"Infinitif",
"bidded":"Past of bid",
"bet":"Infinitif",
"wended":"Past of wend",
"shitted":"Past of shit",
"sheared":"Past of shear",
"wet":"Past of wet",
"quit":"Past of quit",
"smote":"Past of smite",
"worth":"Past of worth",
"undergrow":"Infinitif",
"slayed":"Past of slay",
"sell":"Infinitif",
"sook":"Past of sake",
"pleaded":"Past of plead",
"unwound":"Past of unwind",
"overwritten":"Past Participle of overwrite",
"shove":"Past of shave",
"mowed":"Past of mow",
"drug":"Past of drag",
"interbred":"Past of interbreed",
"drive":"Infinitif",
"slitten":"Past Participle of slit",
"stayed":"Past of stay",
"lead":"Infinitif",
"wear":"Infinitif",
"slide":"Infinitif",
"speed":"Infinitif",
"thought":"Past of think",
"rive":"Infinitif",
"rove":"Past of rive",
"waxen":"Past Participle of wax",
"leave":"Infinitif",
"sting":"Infinitif",
"mistaken":"Past Participle of mistake",
"left":"Past of leave",
"intercut":"Infinitif",
"sake":"Infinitif",
"bleed":"Infinitif",
"outthrew":"Past of outthrow",
"got":"Past of get",
"cut":"Infinitif",
"output":"Infinitif",
"show":"Infinitif",
"speeded":"Past of speed",
"fight":"Infinitif",
"bought":"Past of buy",
"overbent":"Past of overbend",
"swolt":"Past of swelt",
"forbidden":"Past Participle of forbid",
"shrank":"Past of shrink",
"waylaid":"Past of waylay",
"cleped":"Past of clepe",
"besaw":"Past of besee",
"begot":"Past of beget",
"misdeal":"Infinitif",
"threw":"Past of throw",
"retell":"Infinitif",
"swungen":"Past Participle of swing",
"showed":"Past of show",
"split":"Infinitif",
"misbore":"Past of misbear",
"remade":"Past of remake",
"unbent":"Past of unbend"
    }

    conjugaisonIrrReg2 = {
        "sped":"Past Participle of speed",
"struck":"Past Participle of strike",
"brought":"Past Participle of bring",
"outputted":"Past Participle of output",
"ridden":"Past Participle of ride",
"wended":"Past Participle of wend",
"smelt":"Past Participle of smell",
"miscast":"Past Participle of miscast",
"overcast":"Past Participle of overcast",
"overset":"Past Participle of overset",
"slayed":"Past Participle of slay",
"beshone":"Past Participle of beshine",
"dwelled":"Past Participle of dwell",
"slunk":"Past Participle of slink",
"shitten":"Past Participle of shite",
"waylaid":"Past Participle of waylay",
"dug":"Past Participle of dig",
"met":"Past Participle of meet",
"naysaid":"Past Participle of naysay",
"lent":"Past Participle of lend",
"overshone":"Past Participle of overshine",
"inset":"Past Participle of inset",
"stung":"Past Participle of sting",
"clept":"Past Participle of clepe",
"wrung":"Past Participle of wring",
"held":"Past Participle of hold",
"slid":"Past Participle of slide",
"underhung":"Past Participle of underhang",
"rerun":"Past Participle of rerun",
"cast":"Past Participle of cast",
"overslipped":"Past Participle of overslip",
"unwound":"Past Participle of unwind",
"fitted":"Past Participle of fit",
"blessed":"Past Participle of bless",
"won":"Past Participle of win",
"overdressed":"Past Participle of overdress",
"staid":"Past Participle of stay",
"bereaved":"Past Participle of bereave",
"meant":"Past Participle of mean",
"overhanged":"Past Participle of overhang",
"retrod":"Past Participle of retread",
"shitten":"Past Participle of shit",
"underbid":"Past Participle of underbid",
"fled":"Past Participle of flee",
"led":"Past Participle of lead",
"remade":"Past Participle of remake",
"lighted":"Past Participle of light",
"rethought":"Past Participle of rethink",
"offset":"Past Participle of offset",
"leapt":"Past Participle of leap",
"bled":"Past Participle of bleed",
"forleft":"Past Participle of forleave",
"bound":"Past Participle of bind",
"spun":"Past Participle of spin",
"underhewed":"Past Participle of underhew",
"alighted":"Past Participle of alight",
"shut":"Past Participle of shut",
"wedded":"Past Participle of wed",
"bereft":"Past Participle of bereave",
"undercut":"Past Participle of undercut",
"kept":"Past Participle of keep",
"split":"Past Participle of split",
"laid":"Past Participle of lay",
"beheld":"Past Participle of behold",
"besought":"Past Participle of beseech",
"overbought":"Past Participle of overbuy",
"cost":"Past Participle of cost",
"outtold":"Past Participle of outtell",
"dreamt":"Past Participle of dream",
"underlet":"Past Participle of underlet",
"crept":"Past Participle of creep",
"graved":"Past Participle of grave",
"miskept":"Past Participle of miskeep",
"reft":"Past Participle of reave",
"had":"Past Participle of have",
"strided":"Past Participle of stride",
"sneaked":"Past Participle of sneak",
"undergirded":"Past Participle of undergird",
"dived":"Past Participle of dive",
"overspent":"Past Participle of overspend",
"creeped":"Past Participle of creep",
"shat":"Past Participle of shite",
"foretold":"Past Participle of foretell",
"bred":"Past Participle of breed",
"overrun":"Past Participle of overrun",
"durst":"Past Participle of dare",
"drunk":"Past Participle of drink",
"hove":"Past Participle of heave",
"simulcast":"Past Participle of simulcast",
"bidden":"Past Participle of bide",
"told":"Past Participle of tell",
"trod":"Past Participle of tread",
"oversold":"Past Participle of oversell",
"wet":"Past Participle of wet",
"bided":"Past Participle of bide",
"outshone":"Past Participle of outshine",
"showed":"Past Participle of show",
"undergirt":"Past Participle of undergird",
"learnt":"Past Participle of learn",
"shit":"Past Participle of shite",
"forlent":"Past Participle of forlend",
"bent":"Past Participle of bend",
"spoilt":"Past Participle of spoil",
"understood":"Past Participle of understand",
"wrought":"Past Participle of work",
"unbent":"Past Participle of unbend",
"heaved":"Past Participle of heave",
"misread":"Past Participle of misread",
"dwelt":"Past Participle of dwell",
"pent":"Past Participle of pen",
"benimmed":"Past Participle of benim",
"shot":"Past Participle of shoot",
"drug":"Past Participle of drag",
"burst":"Past Participle of burst",
"forspent":"Past Participle of forspend",
"shone":"Past Participle of shine",
"wreaked":"Past Participle of wreak",
"caught":"Past Participle of catch",
"betted":"Past Participle of bet",
"oversewed":"Past Participle of oversew",
"left":"Past Participle of leave",
"bid":"Past Participle of bid",
"rid":"Past Participle of rid",
"reread":"Past Participle of reread",
"knitted":"Past Participle of knit",
"stuck":"Past Participle of stick",
"sprung":"Past Participle of spring",
"input":"Past Participle of input",
"undercast":"Past Participle of undercast",
"relaid":"Past Participle of relay",
"overspilt":"Past Participle of overspill",
"miskenned":"Past Participle of misken",
"strewed":"Past Participle of strew",
"hanged":"Past Participle of hang",
"seethed":"Past Participle of seethe",
"cut":"Past Participle of cut",
"overdrest":"Past Participle of overdress",
"built":"Past Participle of build",
"sewed":"Past Participle of sew",
"overslept":"Past Participle of oversleep",
"overlaid":"Past Participle of overlay",
"burnt":"Past Participle of burn",
"overbent":"Past Participle of overbend",
"slipped":"Past Participle of slip",
"chid":"Past Participle of chide",
"laded":"Past Participle of lade",
"clothed":"Past Participle of clothe",
"underbound":"Past Participle of underbind",
"willed":"Past Participle of will",
"waxed":"Past Participle of wax",
"sat":"Past Participle of sit",
"went":"Past Participle of wend",
"overspilled":"Past Participle of overspill",
"bespread":"Past Participle of bespread",
"overbuilt":"Past Participle of overbuild",
"lost":"Past Participle of lose",
"intercut":"Past Participle of intercut",
"shaped":"Past Participle of shape",
"withheld":"Past Participle of withhold",
"overbred":"Past Participle of overbreed",
"overspread":"Past Participle of overspread",
"wetted":"Past Participle of wet",
"knelt":"Past Participle of kneel",
"thought":"Past Participle of think",
"missent":"Past Participle of missend",
"become":"Past Participle of become",
"blest":"Past Participle of bless",
"mislaid":"Past Participle of mislay",
"rived":"Past Participle of rive",
"writhed":"Past Participle of writhe",
"underfed":"Past Participle of underfeed",
"taught":"Past Participle of teach",
"interbred":"Past Participle of interbreed",
"hung":"Past Participle of hang",
"retold":"Past Participle of retell",
"miskent":"Past Participle of misken",
"shod":"Past Participle of shoe",
"upset":"Past Participle of upset",
"stayed":"Past Participle of stay",
"strowed":"Past Participle of strow",
"dragged":"Past Participle of drag",
"girt":"Past Participle of gird",
"reshot":"Past Participle of reshoot",
"burned":"Past Participle of burn",
"slept":"Past Participle of sleep",
"misshaped":"Past Participle of misshape",
"put":"Past Participle of put",
"crosscut":"Past Participle of crosscut",
"unclothed":"Past Participle of unclothe",
"nimmed":"Past Participle of nim",
"clad":"Past Participle of clothe",
"lipread":"Past Participle of lipread",
"wound":"Past Participle of wind",
"overcome":"Past Participle of overcome",
"undershot":"Past Participle of undershoot",
"heard":"Past Participle of hear",
"withset":"Past Participle of withset",
"knit":"Past Participle of knit",
"mishit":"Past Participle of mishit",
"inlaid":"Past Participle of inlay",
"proofread":"Past Participle of proofread",
"said":"Past Participle of say",
"shined":"Past Participle of shine",
"gilded":"Past Participle of gild",
"shoed":"Past Participle of shoe",
"misunderstood":"Past Participle of misunderstand",
"bet":"Past Participle of bet",
"lit":"Past Participle of light",
"slit":"Past Participle of slit",
"leant":"Past Participle of lean (UK)",
"overslid":"Past Participle of overslide",
"inbred":"Past Participle of inbreed",
"mislearned":"Past Participle of mislearn",
"girded":"Past Participle of gird",
"quit":"Past Participle of quit",
"shit":"Past Participle of shit",
"flung":"Past Participle of fling",
"hamstrung":"Past Participle of hamstring",
"rent":"Past Participle of rend",
"unbound":"Past Participle of unbind",
"set":"Past Participle of set",
"dreamed":"Past Participle of dream",
"underdressed":"Past Participle of underdress",
"rebuilt":"Past Participle of rebuild",
"fit":"Past Participle of fit",
"sought":"Past Participle of seek",
"gnawed":"Past Participle of gnaw",
"outshined":"Past Participle of outshine",
"overheard":"Past Participle of overhear",
"ridden":"Past Participle of rid",
"ground":"Past Participle of grind",
"beat":"Past Participle of beat",
"paid":"Past Participle of pay",
"resent":"Past Participle of resend",
"undressed":"Past Participle of undress",
"sweated":"Past Participle of sweat",
"sent":"Past Participle of send",
"slung":"Past Participle of sling",
"recast":"Past Participle of recast",
"bust":"Past Participle of bust",
"leaned":"Past Participle of lean (US)",
"pleaded":"Past Participle of plead",
"strung":"Past Participle of string",
"broadcast":"Past Participle of broadcast",
"overshined":"Past Participle of overshine",
"crowed":"Past Participle of crow",
"staved":"Past Participle of stave",
"strived":"Past Participle of strive",
"repaid":"Past Participle of repay",
"learned":"Past Participle of learn",
"sweat":"Past Participle of sweat",
"upheld":"Past Participle of uphold",
"misset":"Past Participle of misset",
"bursted":"Past Participle of burst",
"stood":"Past Participle of stand",
"dressed":"Past Participle of dress",
"underdrest":"Past Participle of underdress",
"swung":"Past Participle of swing",
"reset":"Past Participle of reset",
"hurt":"Past Participle of hurt",
"drest":"Past Participle of dress",
"alit":"Past Participle of alight",
"undrest":"Past Participle of undress",
"overbid":"Past Participle of overbid",
"proved":"Past Participle of prove",
"forbid":"Past Participle of forbid",
"spit":"Past Participle of spit",
"forelaid":"Past Participle of forelay",
"busted":"Past Participle of bust",
"bended":"Past Participle of bend",
"bidden":"Past Participle of bid",
"felt":"Past Participle of feel",
"misbegot":"Past Participle of misbeget",
"mislearnt":"Past Participle of mislearn",
"worked":"Past Participle of work",
"beset":"Past Participle of beset",
"hit":"Past Participle of hit",
"bequeathed":"Past Participle of bequeath",
"let":"Past Participle of let",
"underdug":"Past Participle of underdig",
"spilled":"Past Participle of spill",
"unclad":"Past Participle of unclothe",
"wrought":"Past Participle of wreak",
"dealt":"Past Participle of deal",
"hewed":"Past Participle of hew",
"gilt":"Past Participle of gild",
"misdealt":"Past Participle of misdeal",
"forsaid":"Past Participle of forsay",
"misfed":"Past Participle of misfeed",
"forlet":"Past Participle of forlet",
"overslipt":"Past Participle of overslip",
"stunk":"Past Participle of stink",
"sawed":"Past Participle of saw",
"dared":"Past Participle of dare",
"missaid":"Past Participle of missay",
"spoiled":"Past Participle of spoil",
"sunk":"Past Participle of sink",
"shitted":"Past Participle of shit",
"found":"Past Participle of find",
"misheard":"Past Participle of mishear",
"spent":"Past Participle of spend",
"come":"Past Participle of come",
"mowed":"Past Participle of mow",
"sowed":"Past Participle of sow",
"slipt":"Past Participle of slip",
"webcast":"Past Participle of webcast",
"output":"Past Participle of output",
"resold":"Past Participle of resell",
"preset":"Past Participle of preset",
"misspelled":"Past Participle of misspell",
"shrunk":"Past Participle of shrink",
"spilt":"Past Participle of spill",
"rewound":"Past Participle of rewind",
"prepaid":"Past Participle of prepay",
"cleped":"Past Participle of clepe",
"withsaid":"Past Participle of withsay",
"leaped":"Past Participle of leap",
"kenned":"Past Participle of ken",
"begot":"Past Participle of beget",
"beseeched":"Past Participle of beseech",
"shaved":"Past Participle of shave",
"hid":"Past Participle of hide",
"outspent":"Past Participle of outspend",
"sublet":"Past Participle of sublet",
"forlaid":"Past Participle of forlay",
"snuck":"Past Participle of sneak",
"speeded":"Past Participle of speed",
"fed":"Past Participle of feed",
"wept":"Past Participle of weep",
"pled":"Past Participle of plead",
"overpaid":"Past Participle of overpay",
"breastfed":"Past Participle of breastfeed",
"melted":"Past Participle of melt",
"forerun":"Past Participle of forerun",
"underpaid":"Past Participle of underpay",
"spelled":"Past Participle of spell",
"overswung":"Past Participle of overswing",
"outsold":"Past Participle of outsell",
"outbid":"Past Participle of outbid",
"stove":"Past Participle of stave",
"swelted":"Past Participle of swelt",
"outthrust":"Past Participle of outthrust",
"kent":"Past Participle of ken",
"overworked":"Past Participle of overwork",
"misbecome":"Past Participle of misbecome",
"misspelt":"Past Participle of misspell",
"abided":"Past Participle of abide",
"worth":"Past Participle of worth",
"overshot":"Past Participle of overshoot",
"sheared":"Past Participle of shear",
"misspent":"Past Participle of misspend",
"swelled":"Past Participle of swell",
"wed":"Past Participle of wed",
"clung":"Past Participle of cling",
"bidded":"Past Participle of bid",
"underbought":"Past Participle of underbuy",
"read":"Past Participle of read",
"thrived":"Past Participle of thrive",
"made":"Past Participle of make",
"swept":"Past Participle of sweep",
"underlaid":"Past Participle of underlay",
"outthought":"Past Participle of outthink",
"shed":"Past Participle of shed",
"overfed":"Past Participle of overfeed",
"spelt":"Past Participle of spell",
"babysat":"Past Participle of babysit",
"overhung":"Past Participle of overhang",
"gainsaid":"Past Participle of gainsay",
"smelled":"Past Participle of smell",
"run":"Past Participle of run",
"shedded":"Past Participle of shed",
"outrun":"Past Participle of outrun",
"sold":"Past Participle of sell",
"got":"Past Participle of get",
"fought":"Past Participle of fight",
"spread":"Past Participle of spread",
"ridded":"Past Participle of rid",
"penned":"Past Participle of pen",
"podcast":"Past Participle of podcast",
"bought":"Past Participle of buy",
"kneeled":"Past Participle of kneel",
"shat":"Past Participle of shit",
"drank":"Past Participle of drink",
"withstood":"Past Participle of withstand",
"thrust":"Past Participle of thrust",
"misled":"Past Participle of mislead",
"forecast":"Past Participle of forecast",
"underrun":"Past Participle of underrun",
"chidded":"Past Participle of chide",
"thrusted":"Past Participle of thrust"
    }

    be = {
        "am":"Simple present",
        "'m":"Simple present",
        "are":"Simple present",
        "is":"Simple present",
        "'s":"Simple present",
        "are":"Simple present",
        "was":"Simple Past",
        "were":"Simple Past",
        "will be":"Futur",
        "'ll be":"Futur",
        "shall be":"Futur",
        "am being":"Present Progressive/Continuous",
        "'m being":"Present Progressive/Continuous",
        "are being":"Present Progressive/Continuous",
        "is being":"Present Progresssive/Continuous",
        "'s being":"Present Progresssive/Continuous",
        "was being":"Past Progressive/Continuous",
        "were being":"Past Progressive/Continuous",
        "have been":"Present Perfect Simple",
        "has been":"Present Perfect Simple",
        "have been being":"Present Perfect Progressive/Continuous",
        "has been being":"Present Perfect Progressive/Continuous",
        "had been":"Past Perfect",
        "had been being":"Past Perfect Progressive/Continuous",
        "will be being":"Future Progressive/Continuous",
        "'ll be being":"Future Progressive/Continuous",
        "shall be being":"Future Progressive/Continuous",
        "shall have been":"Future Perfect",
        "'ll have been":"Future Perfect",
        "will have been":"Future Perfect",
        "shall have been being":"Future Perfect Continuous",
        "'ll have been being":"Future Perfect Continuous",
        "will have been being":"Future Perfect Continuous",
        "should be":"Conditional Simple",
        "would be":"Conditional Simple",
        "should be being":"Conditional Progressive",
        "would be being":"Conditional Progressive",
        "should have been":"Conditional Perfect",
        "would have been":"Conditional Perfect",
        "should have been being":"Conditional Perfect Progressive",
        "would have been being":"Conditional Perfect Progressive"
           }
    have = {
        "have":"Simple Present",
        "has":"Simple Present",
        "had":"Simple Past",
        "will have":"Future",
        "shall have":"Future",
        "'ll have":"Future",
        "am having":"Present Progressive/Continuous",
        "'m having":"Present Progressive/Continuous",
        "are having":"Present Progressive/Continuous",
        "is having":"Present Progresssive/Continuous",
        "'s having":"Present Progresssive/Continuous",
        "was having":"Past Progressive/Continuous",
        "were having":"Past Progressive/Continuous",
        "have had":"Present Perfect Simple",
        "has had":"Present Perfect Simple",
        "have had having":"Present Perfect Progressive/Continuous",
        "has had having":"Present Perfect Progressive/Continuous",
        "had had":"Past Perfect",
        "had had having":"Past Perfect Progressive/Continuous",
        "will be having":"Future Progressive/Continuous",
        "'ll be having":"Future Progressive/Continuous",
        "shall be having":"Future Progressive/Continuous",
        "shall have had":"Future Perfect",
        "'ll have had":"Future Perfect",
        "will have had":"Future Perfect",
        "shall have had having":"Future Perfect Continuous",
        "'ll have had having":"Future Perfect Continuous",
        "will have had having":"Future Perfect Continuous",
        "should have":"Conditional Simple",
        "would have":"Conditional Simple",
        "should be having":"Conditional Progressive",
        "would be having":"Conditional Progressive",
        "should have had":"Conditional Perfect",
        "would have had":"Conditional Perfect",
        "should have had having":"Conditional Perfect Progressive",
        "would have had having":"Conditional Perfect Progressive"
    }

    temps = {
        ("Present Simple","Present Participle"):"Present Progressive/Continuous",
        ("Past Simple","Present Participle"):"Past Progressive/Continuous",
        ("Present Simple","Past Simple"):"Present Perfect Simple",
        ("Present Perfect Simple","Present Participle"):"Present Perfect Progressive/Continuous",
        ("Past Simple","Past Simple"):"Past Perfect",
        ("Past Perfect","Present Participle"):"Past Perfect Progressive/Continuous",
        ("Future Simple","Present Participle"):"Future Progressive/Continuous",
        ("Future Simple","Past Simple"):"Future perfect",
        ("Future Perfect","Present Participle"):"Future Perfect Continuous",
        ("Conditional Simple","Present Participle"):"Conditional Progressive",
        ("Conditional Simple","Past Simple"):"Conditional Perfect",
        ("Conditional Perfect","Present Participle"):"Conditional Perfect Progressive"
    }

    tempsPassive={
        ("Present Simple","Present Participle"):"Present Simple Passive Voice",
        ("Past Simple","Present Participle"):"Past Simple Passive Voice",
        ("Present Perfect Simple","Present Participle"):"Present Perfect Simple Passive Voice",
        ("Past Perfect","Present Participle"):"Past Perfect Passive Voice",
        ("Future Simple","Present Participle"):"Future Simple Passive Voice",
        ("Future Perfect","Present Participle"):"Future Perfect Passive Voice",
        ("Conditional Simple","Present Participle"):"Conditional Simple Passive Voice",
        ("Conditional Perfect","Present Participle"):"Conditional Perfect Passive Voice",
        ("Present Progressive/Continuous","Present Participle"):"Present Progressive/Continuous Passive Voice",
        ("Past Progressive/Continuous","Present Participle"):"Past Progressive/Continuous",
        ("Present Perfect Simple","Present Participle"):"Present Perfect Simple",
        ("Present Perfect Progressive/Continuous","Present Participle"):"Present Perfect Progressive/Continuous",
        ("Past Perfect Progressive/Continuous","Present Participle"):"Past Perfect Progressive/Continuous Passive Voice",
        ("Future Progressive/Continuous","Present Participle"):"Future Progressive/Continuous",
        ("Future Perfect Continuous","Present Participle"):"Future Perfect Continuous",
        ("Conditional Progressive","Present Participle"):"Conditional Progressive",
        ("Conditional Perfect Progressive","Present Participle"):"Conditional Perfect Progressive"
    }

    def verifyirregularnoun(self,noun):
        if noun in self.irregularnouns:
            return "True"
        else:
            return "False"
    
    def verifyirregularverbs(self,verb):
        if verb in self.irregularverbs:
            return "True"
        else:
            return "False"

    def tempsVerbe(self,token,groupe,tense,mood,aux):
        strTemp = ""
        str = token.text
        strFinal = ""
        strT = ""
        if type(aux) is not list:
            strAux = aux.text
            strAuxDep = aux.dep_
        else:
            strAux = ""
        if str == token.lemma_:
                return "Infinitive"
        if groupe == 1:
            
            for tmps in sorted(self.conjugaisonV1.keys(),key=len,reverse=True):
                if str.endswith(tmps) or str == tmps:
                    strTemp=self.conjugaisonV1.get(tmps)
                    break
        if groupe == 2:
            for tmps in sorted(self.conjugaisonV2.keys(),key=len,reverse=True):
                if str.endswith(tmps):
                    strTemp=self.conjugaisonV2.get(tmps)
                    break
                
        if strTemp == "Présent" and tense == ['Past']:
            strTemp = "Passé simple"
        if mood == ['IMP'] and tense == ['Pres']:
            strTemp = "Impératif"

        if strAux != "" and strTemp != "" and type(aux) is not list:
            if strAux in self.avoir:
                strT = self.avoir.get(aux.text)
                strFinal = self.temps.get((strT,strTemp))
            if strAux in self.etre:
                strT = self.etre.get(aux.text)
                if strAuxDep == "aux:pass":
                    strFinal = self.tempsPassive.get((strT,strTemp))
                else:
                    strFinal = self.temps.get((strT,strTemp))
            
        if strAux != "" and strTemp == "" and type(aux) is not list:
            if strAux in self.avoir:
                strT = self.avoir.get(aux.text)
            if strAux in self.etre:
                strT = self.etre.get(aux.text)
            strFinal = strT
        if type(aux) is list:
            str = aux[0].text.strip()+"_"+aux[1].text.strip()
            if aux[1].lemma_ == "avoir":
                strTemp2 = self.avoir.get(str)
            if aux[1].lemma_ == "être":
                strTemp2 = self.etre.get(str)
            strFinal = self.tempsPassive.get((strTemp2,strTemp))
        return strFinal if aux != None else strTemp