# Generated by Django 4.0.4 on 2022-06-20 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TxLgID', models.IntegerField()),
                ('TxTitle', models.CharField(max_length=300)),
                ('TxText', models.TextField()),
                ('TxAnnotatedText', models.TextField()),
                ('TxAudioURI', models.CharField(max_length=200)),
                ('TxSourceURI', models.CharField(max_length=1000)),
                ('TxtArchived', models.BooleanField(default=False)),
                ('TxTLang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='language.language')),
                ('TxtUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.learner')),
            ],
        ),
    ]
